### ISSUE TITLE
Activity stream doesn't process formatting like bbcode

### ISSUE THREAD

**Issue by jgknight** [esotalk/esoTalk#1]
When viewing a profile, the users activity stream includes posts but the post content displays unparsed bbcode.

**Comment by tobyzerner** [comment]
Additionally, there are some other issues with activity formatting.
- Quotes do not display quite correctly. http://i.imgur.com/ZZDCY.png
- Embedded images display. (They should not, as it can make the post too big for the activity page.)
- Something funky happened with clipping the content here: http://i.imgur.com/0fiv6.png

``` html
<div class='activityBody postBody thing'>
<p><a href='http://esotalk.org/forum/member/26' rel='nofollow external' target='_blank'>http://esotalk.org/forum/member/26</a><br/>Start a private conversation with iugo ( <a href='http://esotalk.org/forum/conversation/start/iugo' rel='nofollow ...</p></div>
</div>
</li>
```
