### ISSUE TITLE
Error when using no table prefix

### ISSUE THREAD

**Issue by toenailsin** [esotalk/esoTalk#10]
When no prefix is specified, one of the tables will clash with an sql keyword (group) and the forum won't work. Perhaps a prefix should be enforced?

**Comment by tobyzerner** [comment]
Or perhaps queries should enforce backticks (`) around table names. I'm not sure if this is doable with the way the ETSQLQuery class is set up, though. I'll look into it.

**Comment by toenailsin** [comment]
Backticks are not ANSI-SQL compliant. If anything is to be used, it should be double-quotes. This can be done in MySQL by using this `SET sql_mode='ANSI';`, and will better allow cross-database compatibility.

**Comment by tobyzerner** [comment]
Hm, I guess enforcing a table prefix seems like a cleaner solution.

**Comment by jgknight** [comment]
Would it be as simple as renaming group to groups or something?

**Comment by tobyzerner** [comment]
Yes, but that would make the table names inconsistent (one would be a plural while the rest would be singular.)

I think enforcing a table prefix is the cleanest solution. Perhaps, on the installation form, making the "_" a constant part of the prefix (put it outside the input) and then the part before would be customizable. That way, if it was left blank, the table prefix would just be "_".
