### ISSUE TITLE
I can't translate

### ISSUE THREAD

**Issue by TomaszGasior** [esotalk/esoTalk#101]
I translate esoTalk to Polish, but I can't translate a few phrases, because esoTalk's author forgot add this.

-- I can't translate "%s new" is conversations list.
Please, in file: core/views/conversations/conversations.php change line 57.
`echo " <a href='".URL("conversation/markAsRead/".$conversation["conversationId"]."?token=".ET::$session->token."&return=".urlencode(ET::$controller->selfURL))."' class='unreadIndicator' title='".T("Mark as read")."'>".Ts("%s new",null,$conversation["unread"])."</a> ";`

-- I can't translate "Controls" in conversation page and member page. This is in JS files...

-- In conversation page I can't translate "Follow" and "Following" AFTER CLICK THIS BUTTON. This is in JS files...

-- I can't translate "Like" and "Unlike" in Like plugin.

-- I can't translate a few phrases in Attachments plugin - eg. "Attach a file", "Drop files to upload".

-- I can't translate SMTP plugin.

-- I can't translate settings Proto skin.

**Comment by tobyzerner** [comment]
Thanks for this. Will fix soon.
