### ISSUE TITLE
You dont have permission to perform this action

### ISSUE THREAD

**Issue by laalkitaab** [esotalk/esoTalk#102]
Whenever I try to disable a plugin or delete a conversation from admin account it says

Error
You do not have permisssion to perform this action.

Please Help

**Comment by tobyzerner** [comment]
Are you using the root administrator account? Need more info to be able to reproduce

**Comment by kilale** [comment]
I get this message every time I want to order a channel on the Administration Page - Channels. 
Creating, editing and deleting channels is no problem, Just the ordering is not possible.
This worked some days ago fine.
