### ISSUE TITLE
Logging redirecting

### ISSUE THREAD

**Issue by PGTarai** [esotalk/esoTalk#105]
When I'm logging in, I'm redirected to www.<myadress>.com/index.php//index.php/

**Comment by FeliciousX** [comment]
Same issue here. Also happens after resetting password screen.

**Comment by FeliciousX** [comment]
instead of redirecting to the proper url, it just appends /index.php to the current url

**Comment by FeliciousX** [comment]
Fixed it! :)

https://github.com/FeliciousX/esoTalk/commit/03952c64cb6e77f2bf9c1cdadc442870f08ff4b0
