### ISSUE TITLE
Sticky enhancements

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#117]
1) Make sticky conversations stick (appear at the top) for guests
2) Show the first couple hundred characters of the first post below a sticky conversation?

**Comment by tvb** [comment]
Should sticky be sticky for logged in users as well?
![screen shot 2014-04-14 at 17 01 28](https://cloud.githubusercontent.com/assets/1263414/2696720/cbfad7b4-c3e5-11e3-9ba2-ae6c875c6793.png)
