### ISSUE TITLE
Error while categorizing channels

### ISSUE THREAD

**Issue by trybowski** [esotalk/esoTalk#127]
Clear instalation of 1.0.0g3. When I try to categorize channels, by drag and drop, I get “cannot contact with server” error. Always. Must be an SQL bug, because after that the slug of “General Discussion” is set to 0 and as a side effect of that, it's not possible to select “General Discussion” channel (I get redirected to “All Channels”).

**Comment by agentphoenix** [comment]
Also got this error. I turned on the debug plugin and here's what it's telling me:

**SQL Error (23000, 1062): Duplicate entry '0' for key 'channel_slug' UPDATE et_channel SET parentId=0, depth='0', lft=3, rgt=4, slug=0 WHERE (channelId='2')**

It's messy, but here's the stack trace that came out of the error:

<pre>The error occurred on or near: C:\ampps\www\anodyne\www\forums\core\lib\ETDatabase.class.php:301
296: $statement = $connection->query($query);
297:
298: // Was there an error?
299: if (!$statement) { 
300: $error = $connection->errorInfo();
301: throw new Exception("SQL Error (".$error[0].", ".$error[1]."): ".$error[2]." \n
".$this->highlightQueryErrors($query, $error[2])."
");
302: } 
303: 
304: // Set up a new ETSQLResult object with the result statement.
Backtrace:
[C:\ampps\www\anodyne\www\forums\core\lib\ETSQLQuery.class.php:676] ETDatabase->query();
[C:\ampps\www\anodyne\www\forums\core\lib\ETModel.class.php:82] ETSQLQuery->exec();
[C:\ampps\www\anodyne\www\forums\core\models\ETChannelModel.class.php:288] ETModel->update();
[C:\ampps\www\anodyne\www\forums\core\lib\ETModel.class.php:95] ETChannelModel->update();
[C:\ampps\www\anodyne\www\forums\core\controllers\admin\ETChannelsAdminController.class.php:127] ETModel->updateById();ETChannelsAdminController->reorder();
[C:\ampps\www\anodyne\www\forums\core\lib\ETController.class.php:180] ::call_user_func_array();
[C:\ampps\www\anodyne\www\forums\core\bootstrap.php:312] ETController->dispatch();
[C:\ampps\www\anodyne\www\forums\index.php:19] ::require();
Additional information:
esoTalk Version (code): 1.0.0g3
esoTalk Version (config):
1.0.0g3 PHP Version: 5.4.20 
Operating System: WINNT 
Server Software: Apache/2.4.6 (Win32) OpenSSL/1.0.1e PHP/5.4.20 mod_wsgi/3.4 Python/2.7.2 
Referer: http://localhost/anodyne/www/forums/admin/channels 
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0 
Request URI: /anodyne/www/forums/?p=admin/channels/reorder.ajax</pre>

Let me know if you need more info.

**Comment by fragglebob** [comment]
I'm getting that same error. Slugs are getting set to 0 somewhere.
