### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Jamesking56** [esotalk/esoTalk#128]
Hello,

Just a feature request.

It would be nice to create a user or validate the email of a user and other actions via an API.

So that I could update esoTalk's member database to match the one from my own system and update, manage etc. accordingly.

**Comment by LimeBlast** [comment]
:+1:

**Comment by jackmcdade** [comment]
+1

**Comment by audacioustux** [comment]
+1

**Comment by Woolworths** [comment]
+1 although going in phpmyadmin and changing 0 to 1 isn't too hard

**Comment by tobyzerner** [comment]
Not something that I'm gonna do for esoTalk, but it will be a first-class consideration for Flarum.
