### ISSUE TITLE
can't confirm their email address

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#133]
User received the mail and verify links, but still show unverified after have visited the link.

test web: http://suom.org

update:
I found that previous users will have problems, but the latest Registered users do not have this problem.
(I recently installed a sendmail for php5.)

**Comment by ciruz** [comment]
Like you said, i have registered myself in your forum, works without any problems. Check if i'm active.

**Comment by tvb** [comment]
@iugo @ciruz see my commit https://github.com/tristanvanbokkem/esoTalk/commit/f836535cddbdf8d6d03d7e26bd509bba33f97901. I think the problem is that we are md5ing the hash again and trying to search with that so it will never match.
