### ISSUE TITLE
Can't Install Plugins, "You do not have permisssion to perform this action."

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#134]
centos 6.2
nginx
PHP 5.5.6

new installation.

**Comment by ciruz** [comment]
How you install plugins?
You only need to copy the whole folder from the plugin you like to install, into _/your-eso-talk-installation-path/addons/plugins/_.
Then you just enable the plugin in admin panel.

Please make sure your permissions are really correct.
Folders and content from _config/_, _uploads/_, _cache/_ must be writeable (chmod 777).
