### ISSUE TITLE
i's are capitalized when I bold it.

### ISSUE THREAD

**Issue by sieu** [esotalk/esoTalk#135]
http://gyazo.com/17d280bd94f6c10806d9cccb40b7da56

How would I fix this? Is it the font used or what?

**Comment by ciruz** [comment]
Do you have a link to your forum for me, where i can test this myself?

**Comment by sieu** [comment]
It''s locally hosted, but I seem to have a temporary fix by changing

body, input, textarea, select {
font-family: open sans,lucida grande,lucida sans unicode,helvetica,arial,sans-serif;
}

to

body, input, textarea, select {
font-family: arial;
}

If the content in the .description class are bolded, you can recreate it with the stock esotalk forums.

**Comment by bensbox** [comment]
It is the used font and the type of it, that is installed on your system. Some fonts do change letters, when they are bold or italic and it changes from Linux, Windows, Mac and even beyond their versions.

In Linux Mint with Firefox for instance, it looks fine. On Windows with Firefox it is the described behaviour.
The font "open sans" seems to be different on both systems and is using an capitalized "i" when being bold.
