### ISSUE TITLE
Random stars appear on a users profile.

### ISSUE THREAD

**Issue by ryanlarson-** [esotalk/esoTalk#136]
![stars](https://f.cloud.github.com/assets/5845892/1608862/1a3daa62-551b-11e3-9cb2-4d64218caca9.PNG)
This happens to myself and others on any web browser we try.

**Comment by ciruz** [comment]
Do you have a url to test it? For me it looks like there's a missing css file.

**Comment by LimeBlast** [comment]
I noticed this myself a couple of days ago - it happens when you enable the Member Notifications plugin.

**Comment by tobyzerner** [comment]
fixed in b0d860252aff1ecdc64e7336b12a1ccea73775a9
