### ISSUE TITLE
Confirm email and reset password

### ISSUE THREAD

**Issue by Butochnikov** [esotalk/esoTalk#141]
Why does this happen?
Some users get link in md5 and some do not?

for some users works

```
where("resetPassword",$hash)
```

for some 

```
where ("resetPassword",md5($hash))
```

---

a little secret:
if the confirmation link does not work, then you need to reset the password, obtain the correct hash. It can be used to confirm the link.

**Comment by tobyzerner** [comment]
don't quite understand the issue? can you please elaborate?

**Comment by Butochnikov** [comment]
some users get an email with broken links
if you look at the links, you will see that some of them in the md5, and some without. Why is that?

**Comment by tobyzerner** [comment]
I need steps to reproduce please :)

**Comment by tvb** [comment]
Experienced the same issue and as far as I can see the problem is that we are md5ing the hash again on select.

``` php
// Find the member with this password reset token. If it's an invalid token, take them back to the email form.
$member = reset(ET::memberModel()->get(array("m.memberId" => $memberId, "resetPassword" => md5($hash))));
```

and

``` php
    // See if there is an unconfirmed user with this ID and password hash. If there is, confirm them and log them in.
    $result = ET::SQL()
        ->select("1")
        ->from("member")
        ->where("memberId", $memberId)
        ->where("resetPassword", md5($hash))
        ->where("confirmedEmail=0")
        ->exec();
```

So it will never match. Fixed it here for me https://github.com/tristanvanbokkem/esoTalk/commit/f836535cddbdf8d6d03d7e26bd509bba33f97901

**Comment by tvb** [comment]
Forgot to include "and" in between the issues in the commit message and therefor this one is not being closed.

**Comment by tobyzerner** [comment]
Nah it's just because the changes haven't been pushed to master yet. (Hover over the little (i) icon next to the commit reference above)
