### ISSUE TITLE
ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by ghostsquad** [esotalk/esoTalk#145]
Unable to "SignUp" using the following information:

name: test
email: testlogin@gmail.com
password: Ca110fDuty

The webpage at http://domain/user/join might be temporarily down or it may have moved permanently to a new web address.

Error code: ERR_CONTENT_DECODING_FAILED

The user DOES get added, as I can see it in the members section from administration. This seems to be related to the email address or the password, as i've been able to add other users like this:

name: test
email: test@domain.com
password: test123

Unfortunately, I can't get PHP to output anything more than the above error message at this time.

Some more information
I'm running this using PHP 5.3 on IIS.
esoTalk 1.0.0g3

**Comment by ghostsquad** [comment]
additional information (replacing my domain with _domain_):

POST http://_domain_/user/join HTTP/1.1
Host: _domain_
Connection: keep-alive
Content-Length: 979
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
Origin: http://_domain_
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarycBS73F8ESsCcISt8
Referer: http://_domain_/user/join?return=%2F
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Cookie: Forum_session=br876ljn0e02dj7tenpqnm49f1

HTTP/1.1 500 Internal Server Error
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Microsoft-IIS/8.0
X-Powered-By: PHP/5.3.26
X-Powered-By: ASP.NET
Date: Thu, 26 Dec 2013 20:48:13 GMT
Content-Length: 1622

``` html
<!DOCTYPE html>
<!-- This page was generated by esoTalk (http://esotalk.org) -->
<html>
<head>
<title>Uh oh! It&#039;s a fatal error...</title>
<meta charset='utf-8'/>
<style type='text/css'>
body {background:#fff !important; font-size:13px; font-family:helvetica neue,helvetica,arial,sans-serif; -webkit-font-smoothing:antialiased; margin:0}
#container {margin:50px auto; width:900px; background:#eaf5f9; padding:20px; line-height:1.5; -webkit-border-radius:5px}
h1 {margin:0 0 20px; font-size:22px; font-weight:normal; color:#23637b}
#container div.details {border:1px dashed #a8cfdd; padding:10px; -webkit-border-radius:3px; margin-bottom:10px; overflow:auto}
a {text-decoration:none}
a:hover {text-decoration:underline}
a:active {color:#1a3e6d}
a {color:#1260ee}
hr {border-style:solid; border-color:#b2cdd8 !important; border-width:1px 0 0; margin:15px 0;}
pre {margin:0; font-size:90%}
.highlight {font-weight:bold; background:#fff}
span.highlight {color:red}
</style>
</head>
<body>

<div id='container'>
<h1>Uh oh! It's a fatal error...</h1>

<p>esoTalk has encountered an nasty error which is making it impossible to do whatever it is that you're doing. But don't feel down - <strong>here are a few things you can try</strong>:</p>
<ul>
<li>Go outside, walk the dog, have a coffee... then <strong><a href='javascript:window.location.reload()'>try again</a></strong>!</li>
<li>If you are the forum administrator, then you can <strong>get help on the <a href='http://esotalk.org/forum'>esoTalk website</a></strong>.</li>
<li>Try hitting the computer - that sometimes works for me.</li>
</ul>
</div>

</body>
</html>
```

So it appears as though esoTalk is "saying" that it's returning a gzipped response, though it isn't. In addition, it's getting a fatal error (custom error handling caught).

Ok, so a little bit more investigation, and enabling esoTalk debugging...

throw new phpmailerException($this->Lang('instantiate'), self::STOP_CRITICAL);

[...\wwwroot\core\lib\vendor\class.phpmailer.php:519] PHPMailer->MailSend();
[...\wwwroot\core\lib\functions.general.php:228] PHPMailer->Send();
[...\wwwroot\core\controllers\ETUserController.class.php:182] ::sendEmail();
[...\wwwroot\core\controllers\ETUserController.class.php:147] ETUserController->sendConfirmationEmail();
ETUserController->join();
[...\wwwroot\core\lib\ETController.class.php:180] ::call_user_func_array();
[...\wwwroot\core\bootstrap.php:315] ETController->dispatch();
[...\wwwroot\index.php:19] ::require();

**Comment by ghostsquad** [comment]
Ok, so it appears, I'm getting this error message because the SMTP Plugin was disabled.

Suggested fix (which I can probably implement):
1. SMTP Plugin is configured as part of installation
2. SMTP Plugin cannot be disabled (if email verification on signup is required)

**Comment by pmache** [comment]
I have disabled SMTP plugin, and everything works fine. Maby it's server, so you must configure SMTP? Do you use apache or ngix?

**Comment by electromoonster** [comment]
Hello!
I have the same problem, I configured SMTP and is the same. :<

How can I fix? Please...

Greetings.

**Comment by ghostsquad** [comment]
I'm running on IIS 8

Note: I can receive emails fine (when SMTP is disabled) when the email address is hosted by the same server as the website. External emails don't work (gmail, live, etc).

In order for external emails to work, I have to configure and enable the SMTP plugin.
