### ISSUE TITLE
Lower minimum number of characters for @mention to 2

### ISSUE THREAD

**Issue by ekee** [esotalk/esoTalk#146]
Dear @esotalk -Toby 

@admin 
@417
@加贝 

I was do mention like this,
@admin @417 worked,But @加贝 wasn't work.
How to @mention a user who's username used not in English or Number?

Best regards.

**Comment by dev-love** [comment]
The same problem exists with usernames, which contain spaces.

**Comment by ekee** [comment]
I find that you need the name which with four characters,then it can work,
usually there was too many username only in two characters,
How to fix it?

**Comment by ekee** [comment]
Thx Very Much! Your team update this project very fast now the days!
Best regards.
