### ISSUE TITLE
I can't install on my local

### ISSUE THREAD

**Issue by favormm** [esotalk/esoTalk#148]
During my installing, after fill database and install it, will direct to http://localhost/esotalk/admin,  and 
Not Found
The requested URL /esotalk/admin was not found on this server.

I direct to http://localhost/esotalk, i can see the index view, but the link not work, the same: Not Found.

**Comment by favormm** [comment]
I answer my question myself. Because esoTalk need rewrite mod, must open it in the httpd.conf.
and change AllowOverride None to AllowOverride All

**Comment by nicekiwi** [comment]
You should mark this as closed.
