### ISSUE TITLE
Private conversations are not private at first.

### ISSUE THREAD

**Issue by ghost** [esotalk/esoTalk#15]
When creating a private conversation, it does not create it as private until you post it, then edit it to add the user to it. So it posts it public for everyone to see first.

This could be a huge problem with sensitive information!

**Comment by tobyzerner** [comment]
I believe this only happens when you click on "Start a private conversation with this member" on a member's profile, or if you click the "PRIVATE" text next to a member's name on the member list. The member isn't initially added to the private conversation as they should be.

**Comment by ghost** [comment]
Right, worded it perfectly.
