### ISSUE TITLE
sign up bug 

### ISSUE THREAD

**Issue by abhisheksinha13** [esotalk/esoTalk#150]
Uh oh! It's a fatal error...

esoTalk has encountered an nasty error which is making it impossible to do whatever it is that you're doing. But don't feel down - here are a few things you can try:

Go outside, walk the dog, have a coffee... then try again!
If you are the forum administrator, then you can get help on the esoTalk website.
Try hitting the computer - that sometimes works for me.

**Comment by tobyzerner** [comment]
Need more information. Add `$config["esoTalk.debug"] = true;` to `config/config.php` and paste the error message here.
