### ISSUE TITLE
SQL syntax error in channel deletion query (empty SQL array)

### ISSUE THREAD

**Issue by jwhsmith** [esotalk/esoTalk#153]
SQL error detected in core/lib/ETDatabase.class.php line 301 . Occurs upon channel deletion (probably when the channel has no conversation in it) : 

SQL Error (42000, 1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 5
DELETE c, m, p FROM et_conversation c
    LEFT JOIN et_member_conversation m ON (m.conversationId=c.conversationId)
    LEFT JOIN et_post p ON (p.conversationId=c.conversationId)
    LEFT JOIN et_activity a ON (a.conversationId=c.conversationId) 
WHERE (c.conversationId IN ())

Empty SQL array detected.

**Comment by tobyzerner** [comment]
This has already been fixed (#129). Please make sure you are using the latest code from GitHub.
