### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Allineer** [esotalk/esoTalk#155]
Hello!

// We don't use PDO's prepared statements as they have some flaws. We emulate parameter binding behaviour

What is flaws? Why you do not using prepared statements and what made you re-invent the wheel?

Why do I must to use table prefixes even when I do not want it?

**Comment by Allineer** [comment]
And Emoticons don't working in the last dev commit.

**Comment by tobyzerner** [comment]
Honestly, I can't really remember. It may have something to do with the fact that PDO doesn't replace more than one binding of the same name... But I'm not even sure there's a use-case for than in esoTalk. 

Unfortunately, the whole pseudo-framework that is esoTalk is a bit of a crude reinvention of the wheel, plagued with bad software design practices. 

Looking at the `from` method in `ETSQLQuery`, it seems the only way to avoid adding the table prefix is if the first character is `(`. Could you make use of that? I will look into adding another optional parameter to opt-out of the table prefix. 

Will also take a look at Emoticons when I get a chance.

**Comment by Allineer** [comment]
Thanks!

Without a table prefixes we getting trouble with "group" table because "group" is reserved word and it's don't escaped with ``````` character.

**Comment by Allineer** [comment]
> PDO doesn't replace more than one binding of the same name

You can transform query with more than one binding of the same name before send it to server:

SELECT `blabla` from `table` where `first` = :param or `second` = :param

SELECT `blabla` from `table` where `first` = :param_1 or `second` = :param_2
->bindValue("param_1", ... )
->bindValue("param_1", ... )

Sorry for my English.

**Comment by tobyzerner** [comment]
I've fixed the "group" table issue in 8b23d71002

Yeah, in hindsight there is probably no _good_ reason for not using PDO bindings, but I don't want to risk breaking anything.
