### ISSUE TITLE
PSR-2 says: "Code MUST use 4 spaces for indenting, not tabs."

### ISSUE THREAD

**Issue by Allineer** [esotalk/esoTalk#161]
PSR-2 says: "Code MUST use 4 spaces for indenting, not tabs."
https://github.com/phpDocumentor/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

May be follow it?
Thanks!

**Comment by tobyzerner** [comment]
esoTalk doesn't follow PSR-2.
