### ISSUE TITLE
error right after 'sign up' page

### ISSUE THREAD

**Issue by lupinehorror** [esotalk/esoTalk#162]
created the admin user during the install but when a new user attempts to register after filling in their details and clicking 'sign up' they get an error.
firefox displays
'Content Encoding Error
The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.
Please contact the website owners to inform them of this problem.'
with chrome i get:
'Error code: ERR_CONTENT_DECODING_FAILED'
don't see anything in the server logs...strangely.
AH! seems like it's to do with the SMTP plugin. it won't work if just localhost is entered...it needs full login details.

**Comment by tobyzerner** [comment]
Glad you solved it for yourself. Next time, here's a good place to start with debugging: http://esotalk.org/docs/debug
