### ISSUE TITLE
Username links should retain the preceding @ symbol

### ISSUE THREAD

**Issue by LiohMoeller** [esotalk/esoTalk#163]
Right now usernames are just converted to links, automatically. This is a bit confusing as the reader might see them as reference links. When 'creative' usernames are used, this applies even more.

I would like to suggest only to link usernames that have a leading @, e.g. @myusername.

**Comment by tobyzerner** [comment]
That is the current behaviour — only words preceded with @ are turned into username links. Unless I'm missing something?

**Comment by LiohMoeller** [comment]
But the @ is visually stripped of the resulting link. That's what I mean.

**Comment by tobyzerner** [comment]
I see. Good call. Reopened.

**Comment by tvb** [comment]
Fixed in a0474f4a0311545f90a8c7e9d9950f5f0374ce18

**Comment by tvb** [comment]
Can be closed now.
