### ISSUE TITLE
Error 404 on every other page than the main

### ISSUE THREAD

**Issue by abedo** [esotalk/esoTalk#169]
I cannot open any other page than index.php:

/esoTalk/user/login?return=%2Fconversations

Not Found

The requested URL /esoTalk/user/login was not found on this server.

**Comment by tvb** [comment]
check your **.htaccess** file for the existence of:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php/$1 [QSA,L]
</IfModule>
```

and in your **httpd.conf** file:

```
AccessFileName .htaccess
```

and

```
<Files ~ "^\.ht">
    Order allow,deny
    Deny from all
    Satisfy All
</Files>
```

**Comment by abedo** [comment]
thanks.

I've changed it in:

$config["esoTalk.urls.rewrite"] = false;

anyway, such settings shouldn't be checked?

**Comment by tvb** [comment]
@abedo Nope, don't change **$config["esoTalk.urls.rewrite"]** to false. Fix it with your htaccess and apache config.

**Comment by Bravehartk2** [comment]
Did the trick!!! Can be closed!
