### ISSUE TITLE
"Report Issues" button

### ISSUE THREAD

**Issue by ghost** [esotalk/esoTalk#17]
Is there any way to add a "Report Issues" button or a "Feedback" button to the page for easy access to this section of GitHub. I think it will cut down on the multiple forums asking "I have this bug, how do I report it".

Just a thought :)

**Comment by jgknight** [comment]
I agree, some type of plugin that provides a feedback button would be cool.  I like how google's feedback button works (takes a screenshot of the page,etc) but that may be beyond our needs.
