### ISSUE TITLE
The 'userMenu' isn't in div class="popupWrapper"

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#171]
Test URL: http://esotalk.org/forum/600-esotalk-1-0-0g3-released
The 'userMenu' should be in 'popupButton button' and 'popupWrapper'.

UA: Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7

![2014-03-22_094716](https://f.cloud.github.com/assets/499364/2489428/010f730e-b164-11e3-8a3a-e75dfa9150f3.png)

**Comment by tvb** [comment]
+1

**Comment by tvb** [comment]
Can be closed?
