### ISSUE TITLE
shipping outdated jQuery Javascript Library

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#173]
currently esoTalk is using jQuery JavaScript Library v1.7 but the current jQuery stable is 1.11.0

Let see if we can update the library with https://github.com/jquery/jquery-migrate/#readme

**Comment by tobyzerner** [comment]
This will take a bit of work... in particular, there's a lot of instances of .live() littered throughout the esoTalk code. One day...

**Comment by shaun-merchant** [comment]
I've updated jQuery to the 2.x branch on my community and corrected the littered .live() and .die() calls in the core JS files and plugins, and currently testing out the changes there. Swapping out jQuery 2.x with jQuery 1.11.0 doesn't result in any obvious issues appearing, but I haven't tested the 1.11.0 branch out on the community, only on local testing.

**Comment by tvb** [comment]
Fun! Want to push it to GitHub?

**Comment by shaun-merchant** [comment]
There's a couple of bugs I need to get round to fixing first, and then I'll push it to GitHub for ya'll to glance over. 😊

**Comment by tvb** [comment]
Und? Squashed the bugs yet?
