### ISSUE TITLE
Unable to resend confirmation email

### ISSUE THREAD

**Issue by simondahla** [esotalk/esoTalk#174]
Getting a fatal error when trying to resend a email confirmation upon new account

![Resend confirmation](http://f.cl.ly/items/1w1g3k0C1H3S3C3x1a0e/Screen%20Shot%202014-03-25%20at%2015.03.42.png)

**Comment by tvb** [comment]
tried it, no issues here:
![screen shot 2014-03-25 at 19 43 02](https://f.cloud.github.com/assets/1263414/2516387/59e13d32-b44d-11e3-8020-765a4fe011a1.png)

using 1.0.0.g4 (develop branch)

[edit]
Actually, confirming the account by clicking on the link in the email does not work. I get redirected to the index without being logged in and when I try to login it states that I have to confirm first...

Receiving a 302
x.x.x.x - - [25/Mar/2014:19:51:48 +0100] "GET /user/confirm/xxxxxxxxxxxxxxxxxx HTTP/1.1" 302 -

**Comment by tvb** [comment]
Update: confirming fixed in https://github.com/tristanvanbokkem/esoTalk/commit/f836535cddbdf8d6d03d7e26bd509bba33f97901

**Comment by tobyzerner** [comment]
Fixed in cb4c2011e4bb74bd66494bfed7c534f104790040
