### ISSUE TITLE
Notifications not being sent

### ISSUE THREAD

**Issue by zconkle** [esotalk/esoTalk#175]
We are having an issue where members following channels or conversations are not getting notifications. The SMTP plugin is enabled.

Users do receive the forgot password email.

We use postmark for SMTP and am not even seeing the messages attempting to be sent out. I am not sure how to go about troubleshooting this and I dont see any logging mechanism in esotalk.

**Comment by zconkle** [comment]
UPDATE: If I go and follow a conversation manually I get a notification. If I just follow a channel I dont receive notifications even though my profile is set to get  notifications from channels I follow.

**Comment by tvb** [comment]
Tested it, works just fine for me. Followed a channel with account a and replied with account b, account a receives an email notification.

testaccount has replied to a channel which you followed: Test Topic!

**Comment by tvb** [comment]
It might be a 1.0.0g3 issue. As I don't receive any channel updates on the official forums as well. I am using 1.0.0g4 (develop brach) myself tho which seems to work just fine.

**Comment by tobyzerner** [comment]
official forums are running the latest develop branch. you guys still having issues?

**Comment by tobyzerner** [comment]
(closing until we can reliably reproduce)
