### ISSUE TITLE
Adopt PSR code style

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#179]
All esoTalk code should be reformatted to adopt some degree of PSR-compatibility.

WinterSilence made a start in #160, but these commits are not feasible to merge in. I think the reformatting really needs to be done without any other alterations to code logic (i.e. no bug fixes or new features), and it needs to be done and merged in immediately so that no intermediate changes get in the way.

Before getting started, though, an exact code style should be defined.

**Comment by WinterSilence** [comment]
Possible to use only PSR-1, PSR-2, it's pure coding style. 
To use PSR-0, PSR-3, PSR-4 need change class\file names, it is too globally or step2 :)

**Comment by tvb** [comment]
Shall we start on this in a seperate branch?

**Comment by tobyzerner** [comment]
Actually, I'm not sure about doing this. It's a huge job and will mess around with development (things will be difficult to merge!) — probably not worth doing for esoTalk (but Flarum will definitely adopt a standard.) It may just be better for me to spend some time writing up coding guidelines for esoTalk's current standard?

**Comment by tobyzerner** [comment]
Yeah, closing this.
