### ISSUE TITLE
"notifications" is not smart enough.

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#18]
I have read the unread post , but notifications still reminding me.

**Comment by tobyzerner** [comment]
Can you please provide additional information and a specific test case, or steps to reproduce?

**Comment by iugo** [comment]
firefox 8.0 (windows)
1. In http://esotalk.org/forum/ see new post.
2. Click "Jump to unread"
3. "notifications" prompted me unread. But I have read that post.

**Comment by iugo** [comment]
Or
1. Click "notifications", But I have not read those posts.
2. "notifications" is no longer notices me.

**Comment by tobyzerner** [comment]
Thanks. After doing some more testing, the following outlines the problems with the notifications system:
- If a notification is shown as a popup in the bottom left corner, and then clicked on, it still appears as unread in the notification badge up the top.
- As you said, if you have an unread notification, and you get to the conversation it refers to some other way, the notification remains unread. I'm not sure if this is as much of a problem (I believe a similar thing occurs in Facebook, for example.)
- Duplicate notifications can occur if someone tags you in a private or starred conversation. (You get two notifications for the same post.)
- Issue #9
