### ISSUE TITLE
Update third-party libraries

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#180]
- farbtastic
- phpmailer
- jsmin

**Comment by WinterSilence** [comment]
I don't understand what is there to discuss? The difference between the versions is small. Fixed some bugs, optimized code. Taken master version. Compatibility checked - everything is fine.

**Comment by tobyzerner** [comment]
Nothing to discuss, just that the pull request couldn't be merged so this needs to be done either in a new pull request (without additional changes like changing the code style) or manually by myself.

**Comment by tvb** [comment]
Lets replace jsmin-php (https://github.com/rgrove/jsmin-php/) with something new as jsmin-php is not being maintained anymore.

---

This project is unmaintained. I stopped using it years ago. You shouldn't use it. You shouldn't use any version of JSMin. There are much better tools available now.

Here are some of them:

Uglify
Google Closure Compiler
JShrink

**Comment by tvb** [comment]
Oef, phpmailer is a big one https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md

**Comment by tobyzerner** [comment]
Not updating jsmin because it works fine and is simpler to integrate than JShrink
