### ISSUE TITLE
add error handling if versions.txt is 404 or if blog feed is unreachable

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#181]
`responseText: "<br />↵<b>Warning</b>:  file_get_contents(http://get.esotalk.org/versions.txt): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
↵ in <b>core/lib/ET.class.php</b> on line <b>160</b>`

**Comment by tvb** [comment]
perhaps change 
`$json = file_get_contents("http://get.esotalk.org/versions.txt");`
into
`$json = @file_get_contents("http://get.esotalk.org/versions.txt");`

until there is a proper 404 check like http://stackoverflow.com/a/4358138/1803216

**Comment by tvb** [comment]
Seems to be fixed already in https://github.com/esotalk/esoTalk/commit/f48d8e9a292628bb49f730e5bd2750e97f830bee and https://github.com/esotalk/esoTalk/commit/06f3b78397b559fcba99523e50d940da535630fd ?

**Comment by tobyzerner** [comment]
Yep!
