### ISSUE TITLE
Manage profile fields

### ISSUE THREAD

**Issue by amwelles** [esotalk/esoTalk#182]
It'd be awesome if profile fields could be added/edited/removed from within the administration pane. Right now it can be done by editing the plugin, but I know that's not best practice.

**Comment by tvb** [comment]
You can already! Just enable the "Profiles" plugin and control the profiles fields from within the admin menu.
![screen shot 2014-04-12 at 19 13 47](https://cloud.githubusercontent.com/assets/1263414/2687658/fcbf7c6e-c265-11e3-844d-a4d1af9eda0c.png)

**Comment by tobyzerner** [comment]
(Make sure you're using develop branch!)

**Comment by amwelles** [comment]
Oh snap! Thanks for that. Looks like I'm using a slightly older version.
