### ISSUE TITLE
404 on icons.png

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#184]
Im not sure where this is called but on esotalk.org/forum I get the follow error:
`GET http://esotalk.org/forum/core/skin/icons.png 404 (Not Found)`

**Comment by tobyzerner** [comment]
I removed icons.png because I thought it was no longer used, but I forgot that it's still used for the search icon in the search box... will have to come up with a solution using font awesome.

**Comment by tvb** [comment]
Fixed here https://github.com/tristanvanbokkem/esoTalk/commit/f4e506b983e590ca3483e833943a47ead4645ebc
and added as pull request.
