### ISSUE TITLE
Class 'ETConversationModel' not found

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#189]
Receive the following error when I browse to /settings on my freshly installed esoTalk installation cloned from the current develop branch:

Fatal error: Class 'ETConversationModel' not found in `core/lib/functions.render.php on line 330`

I am unable to trace the actual location of the error at this point.

**Comment by tobyzerner** [comment]
@tristanvanbokkem Can you confirm fix in a92bfdf?

**Comment by tvb** [comment]
Confirmed.
