### ISSUE TITLE
member?name=Toby , Page Not Found

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#19]
member?name=iugo , Page Not Found too.

**Comment by jgknight** [comment]
Can you give an example URL that link can be found on?  I can't seem to find any profile links that go to a 404 page.

**Comment by iugo** [comment]
http://esotalk.org/forum/member?name=iugo
http://esotalk.org/forum/member?name=Toby

URLs in "quote"

**Comment by jgknight** [comment]
This is a duplicate of bug esotalk/esoTalk#3
