### ISSUE TITLE
post timestamp changes to "context" when searching

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#197]
![screen shot 2014-04-19 at 03 40 58](https://cloud.githubusercontent.com/assets/1263414/2747290/d5657954-c763-11e3-85e7-1b5197e7022a.png)

**Comment by tobyzerner** [comment]
Technically a feature, not a bug... But maybe it's a poor decision. I'll think about it

**Comment by tvb** [comment]
Why would this be a feature?

**Comment by tobyzerner** [comment]
Because search results are shown out of context (without their immediately surrounding posts), and it's a link to show them in their original context.

**Comment by tvb** [comment]
Ah, get it now! Interesting.

**Comment by tvb** [comment]
Hold on, let's change the text from `context` to `show in context`
