### ISSUE TITLE
PHP 5.3.0 required for late static bindings

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#198]
See http://esotalk.org/forum/883-having-problem-with-attachment-plugins

**Comment by tobyzerner** [comment]
Want to maintain support for older PHP 5 releases, so the [code]static[/code] keyword should be amended somehow.

**Comment by tvb** [comment]
You are aware that PHP5.3 is the lowest stable version, right?
I strongly discourage people to use older PHP versions than PHP 5.3..

**Comment by tobyzerner** [comment]
Unfortunately some shared hosts tend to use older PHP versions, so we may as we'll maintain support for them in esoTalk. Flarum will require PHP >5.4

**Comment by tvb** [comment]
Meh, it would be a bad choice to use a shared host which still uses <5.3 but I agree there are still many that do out there.. Do you know how to build a fallback?

**Comment by tvb** [comment]
While writing plugins and sometimes using 3rd party libraries. I am running into PHP 5.3+ features only more and more, like Namespaces. For now I will add a check in the setup() function to see if PHP 5.3 is available but I would like to ask you to reconcinder the decission to maintain support for PHP < 5.3.

**Comment by tobyzerner** [comment]
I have no problems with individual plugins requiring PHP >=5.3, but there's no point in removing support for <5.3 in core.

**Comment by tvb** [comment]
Ok. Using setup() it is.
