### ISSUE TITLE
Negative plugin dependencies

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#199]
Would love see plugin dependencies extended where it would not be able to activate a plugin if another is installed and active.

**Comment by tobyzerner** [comment]
I think it makes more sense to do this manually in the `setup` method of a plugin, e.g.

```
if (in_array("Attachments", C("esoTalk.enabledPlugins"))) return "Cannot be used with Attachments."
```

**Comment by tvb** [comment]
Agreed.
