### ISSUE TITLE
Request: Push-system instead of polling

### ISSUE THREAD

**Issue by paradox460** [esotalk/esoTalk#2]
Currently, it appears this uses polling, which is inefficient.

Ideally, a push technology, like websockets or jabber could be used to improve the speed of threads

**Comment by tobyzerner** [comment]
This is definitely something I want to implement in the future. WebSockets looks quite promising. The bit I'm unsure/uneducated about is how to run a push server with PHP. I assume it'd need some kind of special server setup, in which case most shared servers would not support it.

If anyone can offer any insight as to how this could/should be done, please do!

**Comment by paradox460** [comment]
Yeah, its something that doesn't usually work on apache, you need something like Mongrel2 to make it work properly, unfortunately.

**Comment by ghost** [comment]
I'll just leave this here. http://www.zeromq.org/
See: Well explained method "pub/sub"

**Comment by tobyzerner** [comment]
This is not going to ever be implemented in esoTalk. Definitely will be a first-class consideration in Flarum though.
