### ISSUE TITLE
Add Vietnamese character transliteration in slug

### ISSUE THREAD

**Issue by vukidrock** [esotalk/esoTalk#201]
Yesterday, I edited a little bit in file core/lib/functions.general.php to make Esotalk can convert all Vietnamese character in conversation's URL to original Latin character, and it make URL display clearly in address bar.
http://esotalk.org/forum/894-vietnamese-slug/

**Comment by tobyzerner** [comment]
I'm not going to add this to core since I suspect transliterator_transliterate might take care of it — as long as it is installed.

However, if not, in 6808d503c35b9f5033a288f52fdd54bb98f3c81e I have added an event to the slug function so that plugins can manipulate slugs.
