### ISSUE TITLE
Auto follow private conversation when created

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#202]
When a private conversation is created it would be handy to auto follow that conversation so one would get updates if reply is received.

**Comment by tobyzerner** [comment]
Agreed - but only if the user has checked "Automatically follow private conversations that I'm added to" in setting

**Comment by tvb** [comment]
Oh missed that option in settings - enabled now. Not sure if this already works?

**Comment by tobyzerner** [comment]
Doesn't seem to from a quick test
