### ISSUE TITLE
.button float right reverses order of elements

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#203]
Because we use a `float:right` in the `.button` class, buttons has to be reversed in code to reverse the order on web.

style:

```
.sheet .buttons .button {
margin-left: 10px;
float: right;
}
```

reversed order for login and cancel button in code:

```
<div class='buttons'>
<small><?php printf(T("Don't have an account? <a href='%s' class='link-join'>Sign up!</a>"), URL("user/join")); ?></small>
<?php
echo $form->button("login", T("Log In"), array("class" => "big submit"));
echo $form->cancelButton();
?>
</div>
```

On web it looks ok, buttons are aligned perfectly, first the cancel button and then the login button.
![screen shot 2014-04-23 at 08 54 54](https://cloud.githubusercontent.com/assets/1263414/2774349/d2236a0e-cab4-11e3-9e3e-e928ec92ea60.png)

However, on mobile they won't reverse and are therefor being shown according to the actual code:
![photo1](https://cloud.githubusercontent.com/assets/1263414/2774357/e376f2da-cab4-11e3-8093-71099ea22c25.jpg)

We should remove the `float:right` from class `.button` and put them in a sperate element which holds the `float:right` instead. This will fix the reverse order.

**Comment by tobyzerner** [comment]
I think the reverse order is actually beneficial in this situation. On sheets, the primary button (log in) should be farthest right, and the cancel button to the left of it. But on mobile, when the buttons are aligned to the left, it makes sense for the primary button to be farthest left and the cancel button second.

**Comment by tvb** [comment]
I'm not so sure about that because forms should have a work flow from top left to bottom right. It would make more sense to me if we switched them around on mobile too.
