### ISSUE TITLE
pull-to-refresh for mobile?

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#205]
@tobscure what do you think about adding a pull-to-refresh method for the mobile version? Could be provided by hammer.js, https://github.com/ThrivingKings/RubberBand.js or hook.js

**Comment by tvb** [comment]
Ah forgot about this https://github.com/esotalk/esoTalk/issues/2 Maybe we should still implement this instead.

**Comment by tobyzerner** [comment]
Yeah push is probably more important. Pull to refresh seems like overkill at the moment, the browser refresh button works quite well :)
