### ISSUE TITLE
Max amount of notification should be <= 3 on mobile

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#209]
I noticed this morning my iPhone showed more notifications then there was room to show, therefor it was impossible to scroll. I would propose a change to set the max amount of notification set to <= 3 where the 3rd item would say "Show more" and redirects you to the notifications page.

**Comment by dennisrvink** [comment]
Don't use an iPhone ;)

**Comment by tvb** [comment]
@dennisvink Jealous? :smile:
