### ISSUE TITLE
Add border-bottom to tabs

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#211]
I think a border-bottom to the tabs (e.g.: here: esotalk.org/forum/member/me) would style better.
Just like http://getbootstrap.com/components/#nav-tabs

**Comment by tobyzerner** [comment]
I know this solution is not exactly the same as the bootstrap tabs, but I want to keep the dark primary colour as the background of the selected tab. Good idea to add a border-bottom though to separate them from their content.
