### ISSUE TITLE
scrubber is still zig-zagged

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#213]
Noticed the scrubber to load "Newer" posts is still showing zig-zag (dotted) style so it seems this https://github.com/esotalk/esoTalk/commit/3cd67e737293647286a35a39def0b09d0218441b commit did not removed all of them. We need to edit https://github.com/esotalk/esoTalk/blob/develop/core/skin/base.css#L435 as well.

**Comment by tobyzerner** [comment]
This is an intentional style. That commit was just supposed to remove the zig zag IMAGE, which was replaced with a CSS style. :)

**Comment by tvb** [comment]
Oh, lol.
