### ISSUE TITLE
Make join and login forms extensible

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#215]
Instead of rendering the join and login forms statically, build them with the ETForm class (sections and fields) so that they can be extended.

**Comment by tvb** [comment]
:+1:

**Comment by tvb** [comment]
Oh, I need to update the reCAPTCHA plugin right?

**Comment by tobyzerner** [comment]
Yep! Let me know how you go.

**Comment by tobyzerner** [comment]
Almost forgot to add in events. This should make it possible: abd85663f7928db1b8cdda6cb3609ba29e3e28d0

**Comment by tobyzerner** [comment]
Have you been able to do this @tristanvanbokkem ?

**Comment by tvb** [comment]
Negative. I've been fighting cron these past days. Got that working so I will change reCAPTCHA asap.

**Comment by tobyzerner** [comment]
OK, let me know. Just want to make sure there's not anything wrong before I release 1.0.0g4

**Comment by tvb** [comment]
@tobscure Had some time during lunch. But I am not sure on how to proceed. How do I get the current $form data? Because `$sender->render("user/join")` will only render the field(s) I have added to it.

**Comment by tobyzerner** [comment]
You pretty much want to do the exact same thing that you'd do to add a field to the user preferences form: http://esotalk.org/docs/plugins/members#preferences
1. Hook onto the initJoin event: `handler_userController_initJoin($controller, $form)`
2. Add your section/field
3. In your processing callback, you can get the captcha value with `$form->getValue($key)`. If there's an error, call `$form->error($key, "wrong captcha!")`

**Comment by tvb** [comment]
Almost got it working, it is not yet outputting any error on failure.

``` php
function processRecaptchaField($form, $key, &$data)
{
    $form->error($key, "test!");
}
```

**Comment by tvb** [comment]
Oh, it does add the error to the $form:

``` php
    [errors] => Array
        (
            [recaptcha] => test!
        )
```

It just doesn't show it under the form..

**Comment by tobyzerner** [comment]
Are you outputting a field with the name "recaptcha" using the ETForm::input function? If you look at the code in that function, you'll see how errors are automatically outputted below each field.

If you're not using that function to output the field, though, you'll need to manually output it using `$form->getError($key)`.

**Comment by tvb** [comment]
I am not:

``` php
    function renderRecaptchaField($form)
    {
        // Format the reCAPTCHA form with some JavaScript and HTML
        // retrieved from the Google reCAPTCHA library.
        return "<script type='text/javascript'>
                    var RecaptchaOptions={theme:'clean', custom_translations:" . json_encode(T("mlarray.reCAPTCHA")) . "};
                    $('#recaptcha_image').live('click', function() { Recaptcha.reload(); });
                </script>".
                recaptcha_get_html(C('plugin.reCAPTCHA.public'), '', C('esoTalk.https'));
    }
```

**Comment by tvb** [comment]
Aha, and where do I include `$form->getError($key)` then?

**Comment by tobyzerner** [comment]
Just append it to the return value of your renderRecaptchaField function?

**Comment by tvb** [comment]
But at that point it does not know $key?
`Undefined variable: key in`

**Comment by tobyzerner** [comment]
$form->getError("recaptcha")

**Comment by tvb** [comment]
Got it working!
