### ISSUE TITLE
Unable to send error message to hidden input field

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#217]
When I want to send an error message via

`$form->error("recaptcha_response_field", T("message.invalidCaptcha"));`

 to an hidden input field which is constructed as following:

`<?php echo $form->addHidden("recaptcha_response_field", "manual_challenge"); ?>
`

It won't show the message, but when I reconstruct at a typical input it does work:

`<?php echo $form->input("recaptcha_response_field", ""); ?>`

**Comment by tobyzerner** [comment]
You must output the error for hidden fields manually:

```
<?php echo $form->getError("recaptcha_response_field"); ?>
```
