### ISSUE TITLE
Error while discarding emtpy conversation

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#223]
When discarding an empty conversation I receive the following JS error:

`POST domain/?p=conversation/reply.ajax/0 404 (Not Found)`

**Comment by tobyzerner** [comment]
more specific steps to reproduce? are you logged in as a member, admin, etc.?

**Comment by tvb** [comment]
As regular member and as admin. Couldn't explain it better, hope this helps http://tinypic.com/r/2na06dx/8

**Comment by tvb** [comment]
ps. As you can see, I am not being redirected back to the index as well.
