### ISSUE TITLE
message.fatalError not showing

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#227]
![screen shot 2014-04-30 at 19 41 03](https://cloud.githubusercontent.com/assets/1263414/2844780/abf38ca8-d08e-11e3-87f5-72566305e176.png)

I have checked both my language definitions of the existence of message.fatalError:

`$definitions["message.fatalError"] = "esoTalk has encountered a fatal error. Try again, or <a href='%1\$s'>get help</a>.";`

**Comment by tobyzerner** [comment]
What is the fatal error? (i.e. what is the message when you enable esoTalk.debug?) I'm just interested to know where the fatal error occurs in the request lifecycle, because it could be before the language is loaded

**Comment by tvb** [comment]
You can reproduce this by checking out `master` and set the esoTalk version to 1.0.0g3 in config.php. The Profiles plugin will complain about a duplicate key for `fieldId`. (I know, this is because the Profiles version is still set to 1.0.0g4)
