### ISSUE TITLE
Hide reply form when editing a post

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#230]
Before I submit a pull request for https://github.com/esotalk/esoTalk/commit/ecbafb0719b89d5f75bf7ca1aae4369cce74b070 I would like to talk it over. Wouldn't it better to hide the reply form when editing a post. See

![screen shot 2014-04-30 at 22 55 35](https://cloud.githubusercontent.com/assets/1263414/2847047/db4d9f14-d0a9-11e3-8b66-de4825c62a41.png)

**Comment by tobyzerner** [comment]
I don't think it's necessary. Editing a post is a standalone activity and often the reply area won't even be in the field of view. Even when it is, I've never been distracted by it.

**Comment by tvb** [comment]
But it doens't harm anyone by removing it, it find it more logical and cleaner looking.

**Comment by tobyzerner** [comment]
It harms the codebase. [KISS](http://en.wikipedia.org/wiki/KISS_principle)

**Comment by tvb** [comment]
I don't see why it really hurts the code base. It would only make it more simpler for the end user by not confusing him with two reply forms. But he that is my humble opion ;)
