### ISSUE TITLE
Discard conversation does not discard already uploaded attachments

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#233]
I can click on discard all day long, the attachment won't be removed from disk and session :smile:

![screen shot 2014-04-30 at 23 21 48](https://cloud.githubusercontent.com/assets/1263414/2847386/8d3d0428-d0ad-11e3-820c-b3890871e56e.png)

**Comment by tvb** [comment]
Can we reopen this? Issue is still present. Steps to reproduce: Start new conversation -> Add 2 attachements, one as thumb -> delete conversation. Attachments are still present in db and on disk.

**Comment by tobyzerner** [comment]
Moved to esotalk/Attachments#1
