### ISSUE TITLE
No warning when discarding a reply with attachments in it

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#234]
When we discard an empty conversation there is no need for a warning, but when we discard an empty conversation with attachments in it there should be a warning if we are sure to discard it.

**Comment by tobyzerner** [comment]
While technically it might be the correct behaviour, I think this just adds unnecessary complexity. The purpose of the warning is to prevent the user from losing anything they can't get back — attachments have to be uploaded from somewhere originally, though, so they can just be reuploaded if needed.

**Comment by tvb** [comment]
We need to check if the attachements are being deleted from disk and db tho. I am not sure if this is the case now.

**Comment by tobyzerner** [comment]
Yep. That's a separate issue
