### ISSUE TITLE
No warning when discarding a saved draft reply

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#235]
There is no warning presented when we discarding a saved draft reply.

**Comment by tobyzerner** [comment]
I don't think one is necessary? I would think it's pretty hard to accidentally click on the discard button... I could be wrong?

**Comment by tvb** [comment]
But we do show a warning if you refresh, so why not on discard?

**Comment by tvb** [comment]
And accidentally clicking on discard instead of save is a real life possibility..

**Comment by tobyzerner** [comment]
Hmm, I'm opposed to a warning, but I'll have a play with the arrangement of the buttons.
