### ISSUE TITLE
Move front controller to subdir

### ISSUE THREAD

**Issue by cryptiklemur** [esotalk/esoTalk#239]
For sake of security, its best if you put `index.php` into a directory, like `web/index.php`

**Comment by tobyzerner** [comment]
Agreed, but some shared hosts only give access to the public directory so this is not possible in that scenario. The current directory structure is made secure by the `if (!defined("IN_ESOTALK")) exit;` at the top of every PHP file, and index.html files in each folder to prevent directory listings.

**Comment by cryptiklemur** [comment]
It is possible to resolve that with things like this: http://stackoverflow.com/questions/14889913/how-to-deploy-symfony2-on-a-shared-hosting
