### ISSUE TITLE
Auto-suggest popup lists "undefined"

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#24]
See image: http://i.imgur.com/C5JDk.png

This only seems to occur in Google Chrome. I'm not sure why. Can anyone else please test and confirm?

**Comment by petsagouris** [comment]
I can confirm on Chrome. Haven't looked any deeper other than the javascript code and requests though.

**Comment by tobyzerner** [comment]
Weird. I developed this feature on Chrome and never had a problem with it. The other day, it started happening, and with things like the messages system as well (you'd get "undefined" messages appearing in the bottom-left of the screen.) I worked out it was something to do with `for (var i in array)` loops, and since it had only just started occurring, hoped it was due to a Chrome bug.

Just tried running this code in the Chrome console:

``` javascript
var array = [1,2];
for (var i in array) {
    console.log(array[i]);
}
```

Output is:

```
1
2
function (){return this[this.length-1]}
```

That's the problem. Surely that isn't expected behaviour? Having trouble finding a bug report in the chromium project though.

**Comment by tobyzerner** [comment]
Firefox and Safari both output:

```
1
2
```

when the above code is run, as expected.

**Comment by petsagouris** [comment]
You might want to take a look on [this](http://stackoverflow.com/questions/2914641/javascript-google-chrome-cluttering-array-generated-from-split/2914646#2914646)

**Comment by tobyzerner** [comment]
Thanks, good to know. Will change all `for ... in` loops to standard `for` loops.

**Comment by tobyzerner** [comment]
Seems to have fixed itself on the latest dev version of Chrome, so removing this from the 1.0.0g2 milestone.
