### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#242]
We should add an option to upload a favicon.

![screen shot 2014-05-07 at 11 42 48](https://cloud.githubusercontent.com/assets/1263414/2900791/02b6f48e-d5cc-11e3-8b7b-c6608c7b105e.png)
![screen shot 2014-05-07 at 11 43 02](https://cloud.githubusercontent.com/assets/1263414/2900792/02b74614-d5cc-11e3-864d-a7f9a1a50688.png)

**Comment by tvb** [comment]
Would be nice to have this in 1.0.0g4..

**Comment by tobyzerner** [comment]
It would be nice to have a lot of things in 1.0.0g4, but I have to draw the line somewhere :)

**Comment by Woolworths** [comment]
Well how hard is it to shrink esotalk.org/img/logo.png and upload it as a favicon..??

**Comment by tvb** [comment]
That would bring all kinds if complicated scenarios. E.g.: what if the logo is like Google's logo, how are you going to determine which character should be acted as favicon?

**Comment by tobyzerner** [comment]
I think people can just upload a favicon.png into the root directory of the forum (most browsers check for this file automatically.) Otherwise feel free to write a favicon plugin
