### ISSUE TITLE
Final deletion of posts + viewing deleted posts

### ISSUE THREAD

**Issue by henhouse** [esotalk/esoTalk#243]
Moderators and administrators should be able to fully delete posts off the board. Some threads become very tacky when you have to scroll past lots of gray bars from user's deleted posts.

In an earlier version of esoTalk this was done a nice way by being able to delete-hide a post, but having a "View" option allowing an admin or moderator to view the content that was deleted, without having to restore the post. The restore button was separate.

I feel that there should be a "Permanently delete" option of sorts as well.

**Comment by tvb** [comment]
Lol, you requested exactly the same feature 3 years ago already
https://github.com/esotalk/esoTalk/issues/14

**Comment by henhouse** [comment]
Oh wow, I definitely forgot by now. Annddd you wrote a patch for it (awesome!). Closing this ticket.

**Comment by tvb** [comment]
It was only patch for half the request. Viewing was not included. And besides, @tobscure discarded the patch as he wanted to implement it in a different way.

**Comment by tobyzerner** [comment]
Yep, there are already issues for both of these: #14 and #186 :)
