### ISSUE TITLE
404 on conversation remove

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#245]
The warning message and error in console is showing and dismissing so fast due to the screen reload that a screenshot is all I could grep atm The conversation is being removed successfully however.

![screen shot 2014-05-09 at 08 54 18 1](https://cloud.githubusercontent.com/assets/1263414/2925216/0a3db158-d747-11e3-9646-02e695aff481.png)

**Comment by tobyzerner** [comment]
Can't seem to reproduce, unless I'm doing it wrong? (What exact steps are you taking? Can you reproduce consistently?)

It might be that a polling AJAX request is being made right when the redirect is taking place, and because the conversation no longer exists, it returns a 404.

**Comment by tvb** [comment]
I can reproduce it on esotalk.org/forum. http://tinypic.com/r/2wpqhyw/8
