### ISSUE TITLE
Mobile render weirdness

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#249]
Sometimes I run into some mobile render weirdness I can't really reproduce, but it happens from time to time. Not sure what the issue is.

If I remember correctly this one was showing a deleted conversation.
![photo1](https://cloud.githubusercontent.com/assets/1263414/2936005/33ccfdc4-d83e-11e3-81a5-30a7047064d9.jpg)
![photo2](https://cloud.githubusercontent.com/assets/1263414/2936006/35dc25f4-d83e-11e3-93b6-d11d1321cc31.jpg)

**Comment by tobyzerner** [comment]
The first screenshot looks like the page's JavaScript hasn't been executed... not sure why, but I've never experienced that personally.

The second one is an iOS Safari quirk. Basically, I think fixed positions become absolute when you focus on a text area. I don't think its fixable, but I'll investigate for g5.

**Comment by tobyzerner** [comment]
I think we'll just rely on the second one to be fixed in iOS
