### ISSUE TITLE
Active scrubber character is not being highlighted

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#250]
When browsing to http://esotalk.org/forum/members/name/h the 'H' is not changing to bold where it should as it is the currently active character. When clicking back to the top, e.g.: clicking on the 'G' character the previous character, in this case the 'H' does not get highlighted. However if you move down the list by clicking on 'I' and so on the previous active character get highlighted briefly.

![screen shot 2014-05-10 at 15 11 39](https://cloud.githubusercontent.com/assets/1263414/2936087/03b24ee4-d845-11e3-870a-86b4266925be.png)

**Comment by tobyzerner** [comment]
The active scrubber item reflects the letter of the member being displayed at the very top of the screen. Since the first member is a couple hundred pixels down the page, it's not lighting up.

Will review for 1.0.0g5.
