### ISSUE TITLE
Missing post/converstation/member information on members footer page

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#251]
Not a real issue here but just something I noticed. The post/converstation/member information is missing at the footer when browsing to the /members page. Imo it should be consistent on all pages.

Index:
![screen shot 2014-05-10 at 15 17 39](https://cloud.githubusercontent.com/assets/1263414/2936095/a59583e8-d845-11e3-83fd-f89df66f6fe6.png)

Members:
![screen shot 2014-05-10 at 15 17 02](https://cloud.githubusercontent.com/assets/1263414/2936097/aaa5da0e-d845-11e3-8c54-cb4073e73834.png)

**Comment by tobyzerner** [comment]
It's omitted on every page but the main page to save an extra few queries. Consistency would be nice, but performance is more important in this case.
