### ISSUE TITLE
Unable to set multiple selected items in select()

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#256]
Because [here](https://github.com/esotalk/esoTalk/blob/develop/core/lib/ETForm.class.php#L432) $value is expected to be a string and thus can't it be matched if $value is an array of mulitple selected options.

I have tried to think of a wat to get those matched but I was unable to get it fixed.

**Comment by tvb** [comment]
a print_r($value) at this line https://github.com/esotalk/esoTalk/blob/develop/core/lib/ETForm.class.php#L429 outputs

```
Array
(
    [aankondigingen] => aankondigingen
    [beheerders] => beheerders
)
```

in my case.

**Comment by tobyzerner** [comment]
Would something like this work? (untested) 20cfecc5a8cc36287bf0494e50cae2dd22a9a64f

**Comment by tvb** [comment]
Works perfectly!

**Comment by tobyzerner** [comment]
Just reopening so I don't forget to merge that branch back into devel.
