### ISSUE TITLE
Writing conversation issue?

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#259]
When I wrote http://esotalk.org/forum/976-gmail-takes-on-esotalk-styling on my iPhone I double checked my writing by viewing a preview but it failed to load. Upon posting I did not got redirected back to the main page but it looked like the conversation was not posted. So I clicked again. Checking the index there was a double post. Unfortunately, I am unable to reproduce it atm.

**Comment by tobyzerner** [comment]
I have experienced a similar issue when posting a reply on the esoTalk support forum today, and it seems @henhouse did also (http://esotalk.org/forum/conversation/post/4068). Not sure what could be causing it but needs to be investigated

**Comment by henhouse** [comment]
I'll attempt to reproduce here in a few hours and post back with any findings. Game of Thrones time right now though. :|

**Comment by tvb** [comment]
Experienced another one. After clicking "Post a reply" the yellow loading indicator popups, does it thing and hides again. But the window does not get redirected to the latest post and the "Write a reply" form is still active. I could click again but then it would be a double post. Refreshing (and confirming I want to leave the page) shows my ealier posted reply.

Perhaps we could add a check for double post anyway? Match the hash created from the first post content with the hash of the double post content?

**Comment by tobyzerner** [comment]
I like the idea of automatically checking for a double post. Could you please create a new issue for that?

Will hopefully have some time to investigate the issue at hand within the next few days.

**Comment by tvb** [comment]
Just experienced the same issue on my local esoTalk deployment. I think I have found the issue; [13-May-2014 08:33:58 Europe/Berlin] PHP Fatal error:  require(): Failed opening required 'PHPMailerAutoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.5.10/lib/php') in /core/lib/vendor/class.phpmailer.php on line 575

**Comment by tvb** [comment]
This pull request also fixes email notfications not being send anymore! Just verified this on my own domain.

**Comment by tobyzerner** [comment]
Awesome, thanks!
