### ISSUE TITLE
.form input[type=number] and [type=email] not styled

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#264]
The input type number is missing those nice rounded corners:
![screen shot 2014-05-13 at 22 03 35](https://cloud.githubusercontent.com/assets/1263414/2963346/007fb63e-dada-11e3-9a33-2e1484ca110b.png)

**Comment by tvb** [comment]
Apposed to:
![screen shot 2014-05-13 at 22 06 45](https://cloud.githubusercontent.com/assets/1263414/2963359/22c18c54-dada-11e3-86a3-1e06e5685657.png)

**Comment by tvb** [comment]
[type=email]
![screen shot 2014-05-13 at 22 16 07](https://cloud.githubusercontent.com/assets/1263414/2963462/6fe670b6-dadb-11e3-8fb3-851361db048f.png)

**Comment by tvb** [comment]
Without the addition in colors.css both input types would show without `border-color: #eaeaea;`

**Comment by tvb** [comment]
And wouldn't input[type=*] be a better implementation to adjust them all?

**Comment by tobyzerner** [comment]
No because we don't want input[type=submit] or input[type=button]
