### ISSUE TITLE
baseURL during install wrong?

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#266]
I don't think this is correct?
![screen shot 2014-05-14 at 15 51 58](https://cloud.githubusercontent.com/assets/1263414/2971907/990a7e94-db6f-11e3-94e3-d41a5fb2b845.png)

**Comment by tobyzerner** [comment]
Usually this would not be an issue because a fresh, un-installed esoTalk instance should not be using friendly URLs (it doesn't have any config file to enable them!)

**Comment by tvb** [comment]
I see. Thanks.
