### ISSUE TITLE
Email format is not being verified during join

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#275]
We should verify if the email address format (x @ y . z) and present an error if it doesn't.

**Comment by tobyzerner** [comment]
We're already doing this?
![screen shot 2014-05-17 at 9 14 47 pm](https://cloud.githubusercontent.com/assets/128862/3004754/ad37dde4-ddb8-11e3-9e02-ab89bfe844a0.png)

**Comment by tvb** [comment]
Yeah thought so, I could not get it triggered with the reCAPTHA plugin included.

**Comment by tvb** [comment]
This is my response when I press enter at the email address field:
![screen shot 2014-05-17 at 13 48 46](https://cloud.githubusercontent.com/assets/1263414/3004759/4620f70c-ddb9-11e3-9eea-c804081df92e.png)

**Comment by tobyzerner** [comment]
The email validation takes place in the ETMemberModel's create method. If there are any form errors (e.g. passwords don't match, wrong captcha), then the create method never gets called, thus the email is never validated.

**Comment by tvb** [comment]
Got it!
