### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by Woolworths** [esotalk/esoTalk#276]
![ooopsbug](https://cloud.githubusercontent.com/assets/6524227/3004651/d2325850-ddad-11e3-9358-2e848163162c.PNG)
small bug when starting a thread for just Moderators and Admins and then clicking their names.. just thought i might help :+1: (note that the bug is how it says "Member" instead of "Moderator")

**Comment by tobyzerner** [comment]
This is not a bug; the "0 Members" refers to the number of members that were found matching the search criteria (which in this case is "Moderator".)

**Comment by tvb** [comment]
~~Perhaps change the text to "0 members found matching the search criteria"?~~ Nevermind, it is there already right below.
