### ISSUE TITLE
smtp

### ISSUE THREAD

**Issue by GostlingX** [esotalk/esoTalk#279]
I configure smtp server but not send any email.

**Comment by DaneAU** [comment]
Belive your server needs to have pho SMTP package installed

**Comment by GostlingX** [comment]
php SMTP package?

This is the external mail server:
Le nom d'hôte du serveur : ex.mail.ovh.net
Le port: 587. 
La méthode de chiffrement : STARTTLS.
L'authentification : Mot de passe normal.

this is the error:

Unable to communicate with the server. Wait a few seconds and try again, or refresh the page

**Comment by DaneAU** [comment]
Pear package.

http://email.about.com/od/emailprogrammingtips/qt/PHP_Email_SMTP_Authentication.htm

http://pear.php.net/package/Mail/redirected

**Comment by GostlingX** [comment]
i have pear package and i have checked to send the email via a php file. 

So far everything is ok, but I can not send email with SMTP plugin forum.

[fixed] to the config.php file edit this string: 

$config["plugin.SMTP.auth"] = 'tls';

**Comment by DaneAU** [comment]
Hi Luke,

I don't have time to test this right now, however will in the coming 
days and will see if I encounter the same issue as you.

Maybe in the meantime somoene might have more advice that will get you 
started before this time.

Regards,

**Comment by DaneAU** [comment]
Great to hear you fixed it!
