### ISSUE TITLE
esoTalk attachments error

### ISSUE THREAD

**Issue by atakank77** [esotalk/esoTalk#282]
## esoTalk attachments error.

http://esotalk.org/forum/945-recaptcha

Fatal error: Cannot access property ETPlugin_Attachments::$attachments in /var/www/esoTalk/esotalk.org/public/forum/addons/plugins/Attachments/plugin.php on line 190

**Comment by tvb** [comment]
Has been reported in its own repository already https://github.com/esotalk/Attachments/issues/8
