### ISSUE TITLE
post editor - bug

### ISSUE THREAD

**Issue by Woolworths** [esotalk/esoTalk#284]
if you add a space before and after the bbcode url:
![esotalk1](https://cloud.githubusercontent.com/assets/6524227/3051405/e3600604-e18b-11e3-8989-037e3a81b8db.JPG)
you get this HTML inside your text..
![esotalk2](https://cloud.githubusercontent.com/assets/6524227/3051428/5a0fb01a-e18c-11e3-8ae6-bb099f824e2b.JPG)

Small bug, but still a bug nonetheless!

**Comment by jgknight** [comment]
I think a way to fix this is to modify the regular expressions in core/lib/ETFormat.class.php line 202 to check if it's within brackets, or if the url has [url= behind it.

**Comment by Woolworths** [comment]
youse lot are welcome init
