### ISSUE TITLE
"View More" JS Error

### ISSUE THREAD

**Issue by ghost** [esotalk/esoTalk#285]
I noticed that, after updating to the new version of Esotalk, I can no longer click on the "View More" link at the bottom of the overview page. I get a JavaScript error:

http://cl.ly/image/2c2I2b1t3J26

Any ideas?

**Comment by tobyzerner** [comment]
Only seems to be an issue if $config["esoTalk.urls.friendly"] is not enabled. Fixed in 00208efc56673c15681dd5a66ae60b9462414e95.
