### ISSUE TITLE
Every plugin language definitions file should stay in the repo

### ISSUE THREAD

**Issue by ddinchev** [esotalk/esoTalk#286]
Language definitions should be a file in the plugin repo, with the installation being just copy over of the file in the appropriate folder. It's less error prone during installation, faster and basically will be easier to maintain.

**Comment by dev-love** [comment]
I absolutely agree with ddinchev!

It's quite complicated and a slow process for users to create language files for plugins instead of having them included to work properly immediately after uploading plugin folders.

**Comment by tobyzerner** [comment]
This has been discussed previously: http://esotalk.org/forum/1046-idea-for-language-files/p1#p4306

The correct protocol for plugins is to hardcode the English translation by using [ET::define](http://esotalk.org/docs/localization) in the init method. Then include a list of definitions in the README so they can easily be extracted and translated in other language packs.
