### ISSUE TITLE
Incorrect coding of months in non-english locales

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#288]
The problem is that scrubber doesn't display correct months on the right hand, when different locale is selected, when reading conversation and when PHP is running in Windows environment (it seams it's only in Windows), instead it will display black squares with '?'.

The solution is usage of iconv (at least it works with Russian locale):

Line 127 & 140 in core/views/conversation/index.php

$name = iconv('CP1251', 'UTF-8', strftime("%B", mktime(0, 0, 0, $month, 1))); // ***hotfix

Don't know which solution can handle other languages and codepages in Windows...

**Comment by tobyzerner** [comment]
I don't like this solution for use in the core, because it only solves a single edge case where things work fine everywhere else. I would rather just officially encourage people to not use Windows.

**Comment by inliquid** [comment]
ok
