### ISSUE TITLE
Post quoting, cursor position at end.

### ISSUE THREAD

**Issue by petsagouris** [esotalk/esoTalk#29]
After hitting the quote on a post. The cursor stays at the beggining of the quote. This should be changed and the cursor position should be set to the end of the text. This is mainly because I am watching a lot of posts (already in the esotalk.com/forum/) that are in the form:

```
Message body
> Quoted message body
```

while it should conform to the common:

```
> Quoted message body
Message body
```

**Comment by henhouse** [comment]
I was just coming on here to make an issue for this. Yeah I've noticed a lot of people seem to be quoting above a quote, which naturally looks strange.

Example: http://i44.tinypic.com/23t5ybn.png

**Comment by jgknight** [comment]
At first that's how I thought the new esoTalk was supposed to work. So new and fresh :p! but yeah the cursor should probably be at the end of the post instead.

**Comment by petsagouris** [comment]
There is an interesting answer on that [here](http://stackoverflow.com/questions/511088/use-javascript-to-place-cursor-at-end-of-text-in-text-input-element)
