### ISSUE TITLE
Corrupted sуmbol when veiwing user activity

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#292]
Have found quite annoying issue, when there is Russian language translation used and you are viewing user activity, you see this thing:

![1](https://cloud.githubusercontent.com/assets/6797881/3244008/6b74eb5a-f162-11e3-9576-17b2ce4fd23c.png)

And:
$definitions["Viewing: %s"] = "просматривает: %s";

Then I looked at the code and found what the problem is (more or less the cause) on OnlinrMember.php: 

<?php
$action = ET::memberModel()->getLastActionInfo($member["lastActionTime"], $member["lastActionDetail"]);
if ($action[0]) printf(T("is %s"), (!empty($action[1]) ? "<a href='{$action[1]}'>" : "").lcfirst(sanitizeHTML($action[0])).(!empty($action[1]) ? "</a>" : ""));
?>

lcfirst is calling strtolower(), which seemed to be to problem with UTF-8... Thats why I declared another function with mb_strtolower() and used it instead of lcfirst().

function mb_lcfirst($str)
{
    $str[0] = mb_strtolower($str[0], 'UTF-8'); 
    return $str;
}

However, this made it even more complicated... additional '?' appeared at the begining of phrase, so I decided to remove lcfirst() at all (it's lowercase even in translation fie, so there is no special need for it).

The result:

![2](https://cloud.githubusercontent.com/assets/6797881/3244074/471b80f6-f163-11e3-8274-83f9413b8462.png)

Anyways please use 'mb_' when you process multibyte string. And as I see in comment to mb_strtolower() it's usage sometimes may be quite sophisticated: http://php.net/manual/ru/function.mb-ereg-replace.php#88671

**Comment by tvb** [comment]
Thank you for this submission. On thing you could do to speed up the proposed fix is to fork this repo and submit a pull request with the required fix. @tobscure will quickly examine the proposed fix and if approved it will be merged directly.

**Comment by inliquid** [comment]
Thanks for suggestion, Tristan, I'm acctually not a developer (but learning php now to be able to do some sort of things) but may try to help. I'll need to read through some Github docs at first anyways....

**Comment by inliquid** [comment]
1. I can't reproduce on Debian, seems lcfirst() just doesn't work on UTF-8 on my system: Linux/PHP v 5.5.14.
2. Correct solution anyways would be ether to write a function mb_lcfirst() based on this construction:
   mb_strtolower(mb_substr($string, 0, 1, "UTF-8"), "UTF-8")  - for first letter of input $string

or to remove lcfirst from here (makes no sense since you can lowercase in definitions.php).
