### ISSUE TITLE
Custom cookie name doesn't work

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#293]
When custom cookie name is set, user is not able to log in. F.i.:
$config["esoTalk.cookie.name"] = "Cookie";

**Comment by inliquid** [comment]
ok... it seams it's more complicated...
1. Let's assume everything works. Set cookie name = 'Cookie' it will continue working as usual.
2. Now set it to 'Talk.Cookie'. After you did It, systems breaks and do not let you enter the site. No matter what you do - clean cookes, clean cache, refresh pages, it just doesn't work. Even if you do all above + rollback to name ='Cookie'.
3. In order to let site work you have to do the following:
   a) Rollback to name = 'Cookie'
   b) Do the magic sequence - either register with new user, or go back to the main forum page and press Ctrl-F5 (forces reload cached content including js) and then go to login page
   c) you now able to log in and work with site

It seems that problem with cookies is somehow within jQuery and other js stuff...

**Comment by tobyzerner** [comment]
I can only reproduce this when I put a period (`.`) in the cookie name. Just avoid that and it should be fine.
