### ISSUE TITLE
Error upon Login Page and Sign-Up

### ISSUE THREAD

**Issue by FPSPurple** [esotalk/esoTalk#294]
Hello,

I am encountering an issue where I click on the Sign In page and I get this error on my Cloudflare. I have tried placing False and True variables in the URL related Rewrites and Friendly URLS fields in the config and still nothing.

I get this: http://gyazo.com/5b39ea83959cdf22fff50d9e161e9d8f

On the logins page, I checked and I have this issue where no entry fields appear. This happens even after a clean install.

http://gyazo.com/dc204a68d364f72bf83bb3955ce391c2

---

The URL to the forum is FPSPurple.com/forums

Thanks!

**Comment by tvb** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520
