### ISSUE TITLE
Admin panel view not using CSS from new skin

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#298]
I have created new skin called 'New' - it works fine, but when I go to Admin view, I see that it continues using old 'Default' CSS:

<link rel='stylesheet' href='/forum/addons/skins/Default/resources/styles.css?1400300312'>

**Comment by tobyzerner** [comment]
core/config.defaults.php:

```
$config["esoTalk.adminSkin"] = "Default"; // The active skin for the administrator section.
```
