### ISSUE TITLE
message.CookieAuthenticationTheft appearing when it shouldn't (cookie security is buggy)

### ISSUE THREAD

**Issue by jgknight** [esotalk/esoTalk#30]
When a cookie becomes invalid, the error to the user says message.cookieAuthenticationTheft. I think this message is supposed to tell the user something, but it currently doesn't tell them anything useful.

It should be fixed so it says the cookie has expired or requires re-logging in.

http://i.imgur.com/K1Vwv.png

**Comment by tobyzerner** [comment]
Could someone please post reproducible steps that trigger this error? It may be shown when it shouldn't be.

The error is intended to show when we think that the user's cookie may have been stolen, using this method: http://jaspan.com/improved_persistent_login_cookie_best_practice

**Comment by jgknight** [comment]
- I logged in with the "remember my password" feature on my laptop in my dorm.
- Later, I logged in on a lab computer also with the "remember my password" feature.
- When I came back to my laptop in my dorm, I went to the esotalk forum and it brought up that message.

**Comment by jgknight** [comment]
I received this error without logging in on another computer, so I'm not sure what's triggering it.

**Comment by tobyzerner** [comment]
Still can't reproduce, needs more investigation.

**Comment by tobyzerner** [comment]
For the record, this is explained here: http://thezaz.com/blog/2013/03/persistent_login_cookies.html

There's no easy fix. Perhaps easing up on cookie security is the best option?

**Comment by tvb** [comment]
Interesting read btw. Would like to know how other (non-ssl) sites have implemented this.

**Comment by inliquid** [comment]
Could this be the solution?

http://esotalk.org/forum/conversation/post/5133

**Comment by tvb** [comment]
@tobscure I am still having this [issue](http://esotalk.org/forum/conversation/post/4072). I am using https and persistent cookies on my forums but still  being logged out after a short amount of time. 

``` php
$config["esoTalk.https"] = true;
$config["esoTalk.enablePersistenceCookies"] = true;
```

what else is there what I can do to fix this?

**Comment by tvb** [comment]
@tobscure Ok I noticed things go wrong when I use my mobile to login. I am guessing my session cookie on my desktop becomes invalid after I logged in through the mobile, can we fix that?
