### ISSUE TITLE
preg_replace() eval modifier is deprecated in php-5.5

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#310]
With debug enabled:

![1](https://cloud.githubusercontent.com/assets/6797881/3552794/4642b748-08fc-11e4-8001-9a997c51a8e9.png)

Code should be rewritten as suggested on php.net:
http://php.net/manual/en/function.preg-replace-callback.php

**Comment by tobyzerner** [comment]
Duplicate of #277
