### ISSUE TITLE
Fatal error: Undefined class constant 'MYSQL_ATTR_DIRECT_QUERY' in /home/xxx/public_html/talk/core/lib/ETDatabase.class.php on line 167

### ISSUE THREAD

**Issue by mattmacpherson** [esotalk/esoTalk#320]
Fatal error: Undefined class constant 'MYSQL_ATTR_DIRECT_QUERY' in /home/xxx/public_html/talk/core/lib/ETDatabase.class.php on line 167

I've tried installing on both my dedicated namecheap server and now on my shared hostgator server. I'm getting the exact same error both times.
### Server Info

PHP version 5.3.28
MySQL version 5.6.17
Operating system linux
Architecture     x86_64
Apache version 2.2.27

**Comment by ciruz** [comment]
Take a look at this old issue:
https://github.com/esotalk/esoTalk/issues/97
