### ISSUE TITLE
Use strftime() instead of date() in user profile

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#331]
When viewing last user activity: 
/core/views/member/profile.php:38

Should be

`strftime(T("date.full"), $member["lastActionTime"])`

**Comment by inliquid** [comment]
plus

/core/views/members/member.php:35

**Comment by jgknight** [comment]
Marked as a translation bug - currently these files use the date() function. Needs more investigating but from what I've read, strftime() is better when using languages other than english?  @inliquid can you give an example of what's breaking?

**Comment by tvb** [comment]
Correct.

**Comment by inliquid** [comment]
Existing implementation doesn't work, f.i. when you try to see last user activity when viewing profile (by pointing mouse) - you see template instead of date/time. date() does not understand template T("date.full").
