### ISSUE TITLE
New Plugins problem

### ISSUE THREAD

**Issue by icyberspot** [esotalk/esoTalk#335]
I tried to install some new plugins [such as https://github.com/esotalk/Answers] and [https://github.com/esotalk/Attachments] The plugin appears in Plugin section but I can not see any functionality in the discussions! also when i want to disable them, they give this error [Fatal error: Call to a member function disable() on a non-object in  ..core/controllers/admin/ETPluginsAdminController.class.php on line 88].

This is the same problem I have with installing other plugins as well.
To install them I uploaded the files into plugin folder and added [definitions.Answers.php] to English folder. I have tried them on all versions of esoTalk [master - develop - esoTalk-1.0.0g4] but I get the same problem on all of them.

Have I done anything wrong?
Thanks guys

**Comment by panique** [comment]
Same here! I can reproduce this with ALL plugins.

**Comment by icyberspot** [comment]
I found the solution:
Make sure the plugin's folder name is "Answers" not "Answesr-Master".

**Comment by panique** [comment]
WOW! Thank you sooo much! This really works. My suggestion is that the folder name needs to be exactly like the first part of the Controller.class.php inside, like "MSCaptcha" when the file is named "MSCaptchaController.class.php".

@tobscure @all Would be cool if somebody could note this in the docs or write a fix for this.

**Comment by panique** [comment]
@icyberspot I think we should keep the issue open as this might affect every other user too! For closing a fix should be implemented that allows to name the folder in every possible way OR the plugin handling needs a proper tutorial (maybe on the plugin tab in esoTalk itself and in the documentation etc.). I would commit this by myself but don't have the time currently.

**Comment by icyberspot** [comment]
Sounds good!

**Comment by jgknight** [comment]
I've opened a docs issue. This is not a code bug as it works exactly how it should.
