### ISSUE TITLE
Huge amount of spam posts!

### ISSUE THREAD

**Issue by niutech** [esotalk/esoTalk#347]
My esoTalk forum http://swiftlang.eu/community/ is massively spammed by bots, even though I am using the leatest version and have enabled the reCAPTCHA plugin. How to stop it?

**Comment by tobyzerner** [comment]
You could try the StopForumSpam plugin? http://esotalk.org/forum/1023-stopforumspam

**Comment by niutech** [comment]
I tried it and it helped.
