### ISSUE TITLE
time posted not updated without refresh

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#355]
The time posted is not updated without refreshing the browser.

![screen shot 2014-10-20 at 14 01 24](https://cloud.githubusercontent.com/assets/1263414/4700934/d5d87adc-5852-11e4-9cbb-3092829f0321.png)

**Comment by tobyzerner** [comment]
Only way to fix is to have "time ago" strings generated in JavaScript as well as PHP. More trouble than it's worth for esoTalk.
