### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#356]
from google analytics:

Eliminate render-blocking JavaScript and CSS in above-the-fold content
Your page has 2 blocking script resources and 3 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Remove render-blocking JavaScript:

```
https://www.xyz.nl/…tory,jqueryscrollTo,global.js?1413040618
https://www.xyz.nl/…cookie,autocomplete,search.js?1413040627
```

Optimize CSS Delivery of the following:

```
https://fonts.googleapis.com/css?family=Open+Sans:400,600
https://www.xyz.nl/…ont-awesome,styles,colors.css?1413657032
https://www.xyz.nl/…e/css/emoticons,bookmarks.css?1413043062
```

**Comment by tobyzerner** [comment]
All of these files are essential for page rendering. Not an issue.
