### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#357]
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:

```
https://www.xyz.nl/uploads/avatars/1.png (expiration not specified)
https://www.xyz.nl/uploads/avatars/2.png (expiration not specified)
https://www.xyz.nl/uploads/logo.png (expiration not specified)
https://www.google-analytics.com/analytics.js (2 hours)
```

**Comment by tobyzerner** [comment]
This is more about how your server is set up, not esoTalk's responsibility.

**Comment by tvb** [comment]
Ah you are right, sorry about that.
