### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#358]
Properly formatting and compressing images can save many bytes of data.
Optimize the following images to reduce their size by 11.5KiB (51% reduction).

```
Compressing and resizing https://www.xyz.nl/uploads/avatars/2.png could save 8.6KiB (87% reduction).
Losslessly compressing https://www.xyz.nl/uploads/logo.png could save 2KiB (18% reduction).
Compressing and resizing https://www.xyz.nl/uploads/avatars/1.png could save 853B (88% reduction).
```

**Comment by jgknight** [comment]
If you feel strongly about this please reopen. However there are steps the server administrator can go through to setup gzip compression etc to reduce the bandwidth usage.  I'm going to argue that the disk space saved by compressing off KBs of data is negligible.
