### ISSUE TITLE
Mobile: Size tap targets appropriately

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#359]
Some of the links/buttons on your webpage may be too small for a user to easily tap on a touchscreen. Consider making these tap targets larger to provide a better user experience.
The following tap targets are close to other nearby tap targets and may need additional spacing around them.

```
The tap target <a href="/conversations/algemeen/" class="channel channel-1">Algemeen</a> and 6 others are close to other tap targets see screenshot.
The tap target <a href="/member/1-tristan">Tristan</a> and 11 others are close to other tap targets see screenshot.
The tap target <a href="/13-initiatiev…panelen/unread">4</a> is close to 1 other tap targets.
```

![screen shot 2014-10-20 at 19 48 51](https://cloud.githubusercontent.com/assets/1263414/4706028/699c9e32-5881-11e4-885e-0b5049ec6aa9.png)
![screen shot 2014-10-20 at 19 49 01](https://cloud.githubusercontent.com/assets/1263414/4706029/699d7230-5881-11e4-8093-fdc2c63946b5.png)

**Comment by tobyzerner** [comment]
Don't really care

**Comment by tvb** [comment]
lol.
