### ISSUE TITLE
Jump to original / last / dates (right hand side) not working on Chrome

### ISSUE THREAD

**Issue by bogdanteodoru** [esotalk/esoTalk#362]
Jump to functionality not working on Chrome (38.0.2125.104). Seems to work on Firefox / Safari. No error present in the debug console.

**Comment by jgknight** [comment]
I'm also seeing this on Chrome 39 for OSX.

**Comment by bogdanteodoru** [comment]
Fixed by commit https://github.com/esotalk/esoTalk/commit/2f4fbbf196c033efcda5ccbf45f8fa6396293673
