### ISSUE TITLE
Email recognized as SPAM by Google

### ISSUE THREAD

**Issue by renege** [esotalk/esoTalk#375]
E-mails always get in the spambox of Google Email accounts.....

**Comment by tvb** [comment]
Not an esoTalk problem. Check your SPF record, setup DKIM records and make sure you have an valid PTR record in place.

**Comment by renege** [comment]
Those are good. See:
![schermafdruk 2014-10-30 21 47 47](https://cloud.githubusercontent.com/assets/2900069/4851860/0913ce26-6076-11e4-8429-ab8a60afaa2f.png)

**Comment by Jaspur** [comment]
Mailscore over here is 9.4/10

Also having: `-0.712  HTML_TAG_BALANCE_BODY   HTML has unbalanced "body" tags`. Someone who knows how to fix this?
