### ISSUE TITLE
Chinese search and Chinese usernames is not supported.

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#38]
search test:
http://esotalk.org/forum/conversations/all?search=很好
http://esotalk.org/forum/conversations/all?search=%E5%BE%88%E5%A5%BD

**Comment by jgknight** [comment]
For now, esoTalk will only be supporting languages that use the Latin alphabet. While language packs may help with other languages, things like search and login won't support anything else.  This may change in the future, but it's not priority.

**Comment by tobyzerner** [comment]
It appears that Chinese FULLTEXT search is not possible with a standard MySQL installation: http://blogs.oracle.com/soapbox/entry/fulltext_and_asian_languages_with

In the future, it may be possible to implement Chinese character search if we write a Sphinx adaption for esoTalk.

As for having utf-8 characters in usernames, I've reopened this bug as this should be addressed sometime in the future.

**Comment by petsagouris** [comment]
Greek works on search at least on the esotalk.com forum. (gonna test later on my local installation) (only one bug till now #27).

**Comment by Hakaku** [comment]
All that would be necessary is to check, right before running the fulltext search (in models/ETSearchModel.class), if the string is composed of CJK characters*. And if so, change from a fulltext search, to a search using the LIKE clause (i.e. WHERE content LIKE '%很好%').

*Example: http://blog.2k1y.com/2011/05/detect-cjk-words-in-utf-8-text-via-php.html

Though I can change this easily on my install, I'm not quite sure how to fix it for the "Show matching posts" feature.

**Comment by tobyzerner** [comment]
The performance implications of doing a LIKE search on a big posts table are scary.

**Comment by tobyzerner** [comment]
UTF-8 usernames have been implemented a while ago.

As stated previously, the Chinese search is a MySQL FULLTEXT issue.

**Comment by pluveto** [comment]
CJK usernames still unavailable. Search problem either.
