### ISSUE TITLE
Yesterday is actually the day before

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#389]
I noticed the following scenario. 2 post boths posted `yesterday` according to esoTalk:
![screen shot 2014-11-26 at 15 03 48](https://cloud.githubusercontent.com/assets/1263414/5202354/90795018-757d-11e4-828f-ead64e58565e.png)

However the first one is posted on the 24th so should say `posted 2 days ago`
![screen shot 2014-11-26 at 15 05 51](https://cloud.githubusercontent.com/assets/1263414/5202386/d8e596a4-757d-11e4-8512-b80cf42f6782.png)

the second one is posted on the 25th, so should indeed say `yesterday`.
![screen shot 2014-11-26 at 15 05 56](https://cloud.githubusercontent.com/assets/1263414/5202388/dd52fb64-757d-11e4-83eb-3cabdfb051a3.png)

**Comment by tvb** [comment]
Found it. It should be a round() and not a floor():

``` php
    // If this happened over a day ago, return "x days ago".
    elseif ($ago >= ($period = 60 * 60 * 24)) {
        $days = floor($ago / $period);
        return Ts("%d day ago", "%d days ago", $days);
    }
```

to

``` php
    // If this happened over a day ago, return "x days ago".
    elseif ($ago >= ($period = 60 * 60 * 24)) {
        $days = round($ago / $period);
        return Ts("%d day ago", "%d days ago", $days);
    }
```

I've changed all floor references in the relativeTime() function and it looks good now!

**Comment by jgknight** [comment]
@tvb nice find. Go ahead and issue a pull request if you'd like and I'll merge it in.

**Comment by tvb** [comment]
I'll submit a pull request asap.

**Comment by olivierlambert** [comment]
No pull request yet?

I confirm this, but not only for days, same stuff for the rest: replacing all the `floor()` by `round()` fixed the issue.

All of this in the `core/lib/functions.general.php` file.

**Comment by olivierlambert** [comment]
@jgknight if you want a pull request, I can create one.

**Comment by tvb** [comment]
@olivierlambert go ahead. I have not found the time to sumbit a pull request yet and probably will not find it in the coming weeks. Thanks!

**Comment by olivierlambert** [comment]
Will do :)

**Comment by olivierlambert** [comment]
Done! https://github.com/esotalk/esoTalk/pull/394
