### ISSUE TITLE
Change the "star" and "tag" terminology to something more valid.

### ISSUE THREAD

**Issue by petsagouris** [esotalk/esoTalk#40]
At the moment subscription to discussions is referred to as "starring". Since this isn't a proper verb to define the action taking place I suggest that the term "subscribing" replaces it. 

Furthermore, the verb "tag" doens't really apply since it is closer to "mention" which is more translatable.

These issues stem from the fact that translating that term doesn't actually mean anything in the translations (I am doing the Greek strings atm).

**Comment by tobyzerner** [comment]
I like the idea of changing the "star" terminology to make it more relevant. As you said, "subscribe" could be a good option, or maybe "follow". I will try these out and see what sounds the most natural. 

I chose to use "tag" to be similar to Facebook. However, "mention" is probably a better description of it, especially when the notification is in relation to your post being quoted. I'll try that too.
