### ISSUE TITLE
Server error at conversation reply

### ISSUE THREAD

**Issue by pwFoo** [esotalk/esoTalk#412]
Each reply to an conversation user gets an error message.
I think there is a database upgrade missing during upgrade to latest dev?

> Unknown column 'countPosts' in 'field list

Topic @ esotalk forum
http://esotalk.org/forum/1618-bug-during-reply-with-latest-dev

**Comment by tobyzerner** [comment]
Fixed I think, can you confirm?

**Comment by pwFoo** [comment]
Yes, fixed it! Thanks!
