### ISSUE TITLE
SQL Error When Upgrading To 1.0.0g5

### ISSUE THREAD

**Issue by fcpwiz** [esotalk/esoTalk#416]
Here is the image I get right after I upgrade: http://i.imgur.com/wbO03EM.png

**Comment by jgknight** [comment]
Did you run the upgrade page?  yourforum.com/?p=upgrade

If that doesn't work, try adding `$config["esoTalk.enablePersistenceCookies"] = true;` to your config.php file and then access the upgrade page again.
