### ISSUE TITLE
Navbar expands upon scrolling

### ISSUE THREAD

**Issue by rodrigoargumedo** [esotalk/esoTalk#429]
In reference of https://github.com/flarum/core/issues/81 issue, I encountered a strange bug in the CSS when upon scrolling down of one's thread, totally leaving the search functionality _obstructed_ in the way. Is there a way to fix this?

![bar](https://cloud.githubusercontent.com/assets/7613139/7643618/5ae7514c-fa58-11e4-9f9d-cbd9c866e7bd.JPG)

**Comment by jsonnull** [comment]
I fixed this recently in an updated skin I made. The short of it is, on the default theme the user menu and new conversation button are floated to the right of the logo or conversation title. So when the conversation title grows to a certain point, the usermenu drops down. A fix is to add a sufficient right padding on the inner wrapper of the header and then apply a corresponding negative right margin to the right-aligned content.

For an example of how this is done, see how the default theme right-aligns the post count and last post information on the conversations list. This technique should be applied to the header as well.
