### ISSUE TITLE
Can esotalk1.0.0g1 update to new version ?

### ISSUE THREAD

**Issue by adrianday** [esotalk/esoTalk#43]
Can esotalk1.0.0g1 update to new version ? Or need re-install when i need update

**Comment by petsagouris** [comment]
This can't be a bug report. Please post only bug reports or feature requests on the tracker as it is meant for use for the developement of esotalk. For general questions and so forth, use the forums.

**Comment by adrianday** [comment]
OK I will comment on forum.
