### ISSUE TITLE
API link in documentation is incorrect

### ISSUE THREAD

**Issue by jsonnull** [esotalk/esoTalk#435]
On the esoTalk website, the documentation landing page (http://esotalk.org/docs) links to the "full esoTalk API Reference" at http://esotalk.org/api. This link has not worked for me since I found out about the project several months ago.

A working address, which I only happened upon recently, is http://esotalk.org/api/index.html.

Of course the API reference is somewhat superior to tracking down the method in the actual source file.

**Comment by jgknight** [comment]
Can you please open an issue in the docs repo https://github.com/esotalk/docs

I'm guessing it's just an nginx config change to point to the correct index/default page.
