### ISSUE TITLE
Automatic embedded YouTube videos will fail over https

### ISSUE THREAD

**Issue by henhouse** [esotalk/esoTalk#437]
I've noticed that if you're website is being served over HTTPS, a YouTube video will fail to embed since it's attempted to get the non-https embed resource, and therefore rejects it.

Console error on inspect reads:
`Mixed Content: The page at 'https://www.example.com/forums/8917-thread-name-here' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/videoidhere'. This request has been blocked; the content must be served over HTTPS.`

**Comment by mroi** [comment]
Are you running the latest Git version? 5f503f6f should have fixed this.

**Comment by tobyzerner** [comment]
:+1:

**Comment by henhouse** [comment]
Indeed it did. :( Sorry for not noticing.

**Comment by mroi** [comment]
Thank you for testing and confirming that it works as intended.
