### ISSUE TITLE
ETPluginsAdminController.class.php on line 59

### ISSUE THREAD

**Issue by erwinowak** [esotalk/esoTalk#440]
Notice: Use of undefined constant SORT_NATURAL - assumed 'SORT_NATURAL' in /forum/core/controllers/admin/ETPluginsAdminController.class.php on line 59 Notice: Use of undefined constant SORT_FLAG_CASE - assumed 'SORT_FLAG_CASE' in /forum/core/controllers/admin/ETPluginsAdminController.class.php on line 59 Warning: ksort() expects parameter 2 to be long, string given in /forum/core/controllers/admin/ETPluginsAdminController.class.php on line 59

Plugins tabs.

**Comment by tobyzerner** [comment]
I guess we require PHP 5.4+... http://php.net/manual/en/function.sort.php

**Comment by jgknight** [comment]
Could we replace instances of SORT_NATURAL/sort() with the natsort() function ?
http://php.net/manual/en/function.natsort.php

At least as a workaround for those with problems. Requiring php 5.4 doesn't seem like a big deal.

**Comment by erwinowak** [comment]
Issue has been solved ;)
