### ISSUE TITLE
Avatar Issue.

### ISSUE THREAD

**Issue by panda** [esotalk/esoTalk#441]
Hey!

Thanks for providing me with an amazing forums software! But I ran into an issue the other night. My users cannot set a avatar, when a user tries to set a avatar and proceeds with save changes they get sent into the white screen of death (blank page)

Here's a picture explaining it.

https://pnada.co/i/yHfSpTC.png

**Comment by panda** [comment]
Any reply on this would be appreciated.

**Comment by tvb** [comment]
Post your apache2/httpd error logs. The reason should be visible there.

**Comment by jgknight** [comment]
I'm going to guess you don't have your web server configured correctly.  Look through your web server logs and see if there are any errors.  Without anything else to go on, it's hard to say why.

Also please post this on the esoTalk support forum, though we can open this issue back up if it's determined to be an actual problem with the code. http://esotalk.org/forum
