### ISSUE TITLE
Show the post link

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#45]
Example:
http://esotalk.org/forum/27-an-introduction-to-esotalk-s-code?search=feedback

Having read the search results, I would like to return to the full post. But there is no corresponding page link.

**Comment by tobyzerner** [comment]
You can either click the 'x' in the search input to clear the search, or click the post's time ("16 hours ago") if you want to go back to the part of the conversation where that post is.

Perhaps, for search results, the time string ("16 hours ago") should say "Context" instead?

**Comment by adrianday** [comment]
"Perhaps, for search results, the time string ("16 hours ago") should say "Context" instead?"
I think add a title"click to read the full context"  for the link "16 hours ago"  is better.
