### ISSUE TITLE
esotalk.org down

### ISSUE THREAD

**Issue by k0nsl** [esotalk/esoTalk#453]
Perhaps its only a temporary problem, but I haven't been able to access it for the entire day. Just a heads up, but I bet you're already aware about it.

**Comment by mroi** [comment]
Does you closing this report mean it works for you again? Because I still cannot reach the website.

**Comment by k0nsl** [comment]
@mroi: No, it does not work. I just realised that this project isn't being maintained so I would assume they simply got rid of the site. As it tells us in the `README.md` (and which I overlooked), Flarum is the successor to this project.

**Comment by mroi** [comment]
True, and I know about Flarum, which is still in beta. Anyways, it does look like the site is down by mistake, because even the Flarum site links back to esotalk.org in some prominent place. Let’s just wait and see if the page comes back up.

**Comment by tobyzerner** [comment]
Sorry, the server I'm hosting it on is broken and I haven't gotten around to fixing it. Will do eventually, it won't be gone forever :)
