### ISSUE TITLE
Using URL to post # scrolls too far down

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#46]
http://esotalk.org/forum/3-esotalk-1-0-0g1-released/p1#p25
Screenshot: http://i427.photobucket.com/albums/pp353/iugo/jietu/2.png

It should be http://i427.photobucket.com/albums/pp353/iugo/jietu/1.png

**Comment by jgknight** [comment]
Could you elaborate on exactly what the bug is?

**Comment by jgknight** [comment]
Ah I think I understand.  Going to post # 25 should have Meow's post at the top of the screen, but when you go to it, the page scrolls down too far. I went ahead and changed the title. Please try to make the title more descriptive when possible.

**Comment by iugo** [comment]
eh... Sorry for my poor english.

**Comment by intellecat** [comment]
the discussion which "#p25" point to is partly covered by the conversationHeader
