### ISSUE TITLE
mysql error 

### ISSUE THREAD

**Issue by deveshruttala** [esotalk/esoTalk#473]
I have downloaded and ran the file **index.php** but received an error saying  
![123](https://user-images.githubusercontent.com/45329115/84383157-5d67fa80-ac09-11ea-95a2-812993b25f1f.png)

what to do with this error I am  a learner in this field so please clarify this problem to me and please tell me a method to solve this issue

**Comment by esyede** [comment]
Just change this line https://github.com/esotalk/esoTalk/blob/a8a9c0b4782777d81a6802a4da0cf55494b9817c/core/controllers/ETInstallController.class.php#L301

into this:
```php
if (!extension_loaded("mysqli")) $errors[] = T("message.greaterMySQLVersionRequired"); 
```

Or just comment that line
