### ISSUE TITLE
style not working on localhost

### ISSUE THREAD

**Issue by neosin** [esotalk/esoTalk#53]
Just installed and the forum works but the style is not displaying

<link rel='stylesheet' href='/esotalk/cache/css/base,styles.css?'>

I visit the style link to verify if it is loaded and it says "The page you're looking for could not be found."

Not sure why the error happens, maybe path error?

**Comment by neosin** [comment]
is there a cache bug in the script?
When I look in the header of the page it shows these but visiting the link of each gives page not found error.
rel='stylesheet' href='esotalk/cache/css/base,styles.css?
src='esotalk/cache/js/jquery,jquery.misc,jquery.history,jquery.scrollTo,global.js?
src='esotalk/cache/js/jquery.cookie,autocomplete,search.js?

**Comment by tobyzerner** [comment]
Is your cache directory writable? Are the any files in cache/css and cache/js?
