### ISSUE TITLE
Date format in Timeline

### ISSUE THREAD

**Issue by TomaszGasior** [esotalk/esoTalk#57]
I write polish language for esoTalk, but I don't good speak in English, so I'm sorry for my errors. :)

In Polish other date format is in Timeline and other date format is in post date.
For example: January in Polish in Timeline is "Styczen" and in post date is "stycznia".
So, please of feature edit date (month) format in Timeline in language file.

**Comment by tobyzerner** [comment]
Duplicate of #50
