### ISSUE TITLE
Login success -- sent to incorrect URL

### ISSUE THREAD

**Issue by henhouse** [esotalk/esoTalk#6]
1. Login to a forum with an existing account.
2. Get sent to a page with URL such as:

http://www.mysite.com/esotalk/index.php/index.php/http://www.mysite.com/esotalk/index.php/

**Comment by iugo** [comment]
Issue #47 
https://github.com/esotalk/esoTalk/issues/47

**Comment by shidianxia** [comment]
check  config/config.php in these lines
$config["esoTalk.urls.friendly"] = true; 
$config["esoTalk.urls.rewrite"] = true; 
if these lines are correct，then check .htaccess file is located in the wwwroot,esle:
create a .htaccess file with the following content:
<IfModule mod_rewrite.c> 
RewriteEngine On 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteRule ^(.*)$ index.php/$1 [QSA,L] 
</IfModule>
