### ISSUE TITLE
Replace homebrew database class with multi-dbms ORM

### ISSUE THREAD

**Issue by katanacrimson** [esotalk/esoTalk#62]
Suggestion: replace ETDatabase.class.php and ETDatabaseStructure.class.php with RedBean.

https://github.com/gabordemooij/redbean

Much more powerful, and also not dbms-specific (it'll allow use with Postgres and sqlite (sqlite for dev purposes).

**Comment by tobyzerner** [comment]
In an ideal world, I would love to do this. But realistically it means rewriting a lot of code which I don't have time to do. (I admit I made a poor decision initially to write homebrew stuff)
