### ISSUE TITLE
Use Gravatar for providing avatars

### ISSUE THREAD

**Issue by katanacrimson** [esotalk/esoTalk#63]
Instead of having file uploads of images for avatars, perhaps gravatar should be considered instead?  This removes the need for file uploads which is a common attack vector.

So long as the user has an email address, you can obtain their gravatar easily.

http://en.gravatar.com/site/implement/

I've got a lightweight library available as well (php 5.3+) for gravatar integration if that'd help - licensed under the MIT license as well.

https://github.com/damianb/gravatarlib

**Comment by samsong** [comment]
I will create a plugin for this perhaps.
Or just insert it directly into the code

**Comment by tobyzerner** [comment]
Added a new Gravatar plugin to repo. Had to do some refactoring to the avatar function in the core to make this possible. Now the avatar() function expects an array of member details (including the email) rather than just the memberId and avatarFormat.
