### ISSUE TITLE
url encoding issues

### ISSUE THREAD

**Issue by pojka** [esotalk/esoTalk#64]
hi, can see some issues with urlencoding on the forum, for example at http://esotalk.org/forum/

1: /forum/conversations/all/?search=order by replies

spaces should be urlencoded to %20

2: '/forum/conversation/star/105?token=440f1a4ea53be&return=%2F'

the & should be urlencoded to & amp;

**Comment by samsong** [comment]
1. already seeing a %20 instead of spaces
2. the & should not be urlencoded as it is a separate parameter

**Comment by pojka** [comment]
I'm still seeing unencoded spaces - http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Fesotalk.org%2Fforum%2Fconversations%2Fall

In terms of the &amp - my understanding is that ampersands in href should always be encoded. I'm not alone:

http://mrcoles.com/blog/how-use-amersands-html-encode/
http://htmlhelp.com/tools/validator/problems.html#amp

however, running validation no longer complains about this

**Comment by tobyzerner** [comment]
No longer the case in HTML 5. http://stackoverflow.com/questions/17374087/html5-and-ampersands-in-urls
