### ISSUE TITLE
Incorret RegExp for bold on plugins/BBCode/plugin.php

### ISSUE THREAD

**Issue by paulocoutinhox** [esotalk/esoTalk#65]
I think that bold regexp is wrong, because you use the character "|" instead of "/" in first regexp character, look:

// Bold: [b]bold text[/b]
$sender->content = preg_replace("|[b](.*?)[/b]|si", "<b>$1</b>", $sender->content);

// Italics: [i]italic text[/i]
$sender->content = preg_replace("/[i](.*?)[\/i]/si", "<i>$1</i>", $sender->content);

File:
esoTalk / plugins / BBCode / plugin.php

Line:
102

OBS: All regexp of BBCODE start with "/" but only "bold" regexp is starting with "|".

**Comment by kyso** [comment]
Running some tests shows that this might be purposeful. http://www.solmetra.com/scripts/regex/index.php
