### ISSUE TITLE
%2F in url 

### ISSUE THREAD

**Issue by MrAndreius** [esotalk/esoTalk#74]
The method uses urlencode($this->selfURL)

resulting in the URL get an error %2F  instead of a slash /
ets. http://esotalk.org/forum/user/login?return=%2Fconversations%2Fall

// If the user IS NOT logged in, add the 'login' and 'sign up' links to the bar.

```
    if (!CMF::$session->user) {
        $this->addToMenu("user", "login", "<a href='".URL("user/login?return=".urldecode($this->selfURL))."' class='link-login'>".T("Log In")."</a>");
        $this->addToMenu("user", "join", "<a href='".URL("user/join?return=".urlencode($this->selfURL))."' class='link-join'>".T("Sign Up")."</a>");
    }
```

can use    urldecode($this->selfURL)    :+1:    ???

**Comment by tobyzerner** [comment]
Having %2F in the URL is the correct behaviour, as we want the forward-slashes to be encoded. From my testing the redirect appears to function correctly. Is the issue you have purely aesthetics or am I missing something?

**Comment by MrAndreius** [comment]
more aesthetic issue :)
