### ISSUE TITLE
Incorrect url in /lib/ET.class.php

### ISSUE THREAD

**Issue by Hakaku** [esotalk/esoTalk#77]
The following line needs to be updated in /lib/ET.class.php, otherwise it generates the PHP warning "Cannot use string offset as an array in... at line 151".

```
$json = file_get_contents("http://get.esotalk.com/versions.txt");
```

Edit: For that matter, esotalk.com is also mentioned in the following files as well (though nothing critical):
- \skins\Proto\skin.php
- \views\message.master.php

**Comment by tobyzerner** [comment]
All esoTalk URLs are already .org in the master branch.
