### ISSUE TITLE
Member autocomplete doesn't work when username has a space

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#83]

**Comment by iangcarroll** [comment]
Usernames don't have spaces. This isn't a valid issue...

**Comment by tobyzerner** [comment]
You're right. I should have added that this issue is only relevant to a customized installation of esoTalk that I've been working with which allows spaces in usernames.

Perhaps it could be solved by making use of non-breaking spaces for @mentions

**Comment by iangcarroll** [comment]
Would be cool to open-source it. We can't help with a closed version of your software.

**Comment by Nephets** [comment]
This _is_ his issue tracker. Have a breather yeah?

**Comment by tobyzerner** [comment]
fixed in 978463864f03fb76212ad5747475df2ee78bf2ad
