### ISSUE TITLE
Bugs with post auto-expansion in Firefox

### ISSUE THREAD

**Issue by Hakaku** [esotalk/esoTalk#85]
1. When a large post is created and the textbox expands vertically, the beginning of the post will start disappearing after a certain point. Unlike Internet Explorer, no scrollbar appears immediately within the box unless you keep adding several more lines downwards.

This also applies when editing a post. The box is usually not big enough for the content, and, since no scrollbar appears, a good part of the text remains hidden.
1. Once the textbox is vertically long enough, it becomes noticeable that any press of the backspace, undo (ctrl+z), or deletion of highlighted characters will cause the browser to jump all the way up to the top of the screen.

**Comment by tobyzerner** [comment]
I think this was fixed a while ago.

**Comment by Hakaku** [comment]
The first problem wasn't fully addressed. Just type any letter, hold enter, then scroll back up and you should notice that the letter/line you initially typed disappeared. (Firefox)

And if you go to edit a post that's larger than the default box size, all the extra content will be hidden.

**Comment by tobyzerner** [comment]
Ah, I see what you mean. Better? d5dc47bd0eb2bd029fdd8fd9b71b6ed3e0a55a45

**Comment by tobyzerner** [comment]
wait, no, it made something else go wrong in chrome

**Comment by tobyzerner** [comment]
Think I fixed it now.

**Comment by Hakaku** [comment]
Edit: (I just scrapped what I said); it works now! I just forgot to purge the cache. Thank you again!
