### ISSUE TITLE
Attachments plugin activation error

### ISSUE THREAD

**Issue by selmardaga** [esotalk/esoTalk#87]
SQL Error (42000, 1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=InnoDB DEFAULT CHARSET=utf8' at line 3
CREATE TABLE `et_attachment` (

) ENGINE=InnoDB DEFAULT CHARSET=utf8
The error occurred on or near: C:\wamp\www\eso2\lib\ETDatabase.class.php:290

285:    $statement = $connection->query($query);
286: 
287:    // Was there an error?
288:    if (!$statement) {
289:        $error = $connection->errorInfo();
290:        throw new Exception("SQL Error (".$error[0].", ".$error[1]."): ".$error[2]." \n<pre>".$this->highlightQueryErrors($query, $error[2])."</pre>");
291:    }
292: 
293:    // Set up a new ETSQLResult object with the result statement.

Backtrace:

[C:\wamp\www\eso2\lib\ET.class.php:116] ETDatabase->query();
[C:\wamp\www\eso2\lib\ETDatabaseStructure.class.php:199] ET::SQL();
[C:\wamp\www\eso2\plugins\Attachments\plugin.php:25] ETDatabaseStructure->exec();
[C:\wamp\www\eso2\controllers\admin\ETPluginsAdminController.class.php:123] ETPlugin_Attachments->setup();
ETPluginsAdminController->toggle();
[C:\wamp\www\eso2\lib\ETController.class.php:180] ::call_user_func_array();
[C:\wamp\www\eso2\index.php:322] ETController->dispatch();
Additional information:

**Comment by tobyzerner** [comment]
The Attachments plugin is currently in development.
