### ISSUE TITLE
Adding external files

### ISSUE THREAD

**Issue by arturhns** [esotalk/esoTalk#88]
There is a problem when adding external files to a new skin. The problem is caused by the way that head is built.

Example:

```
class ETSkin_Theme extends ETSkin {

    public function handler_init($sender) {
        $sender->addCSSFile('http://fonts.googleapis.com/css?family=Open+Sans');
    }
}
```

Becomes:

```
<link rel="stylesheet" href="/path/to/root/http://fonts.googleapis.com/css?family=Open+Sans?">
```

It can be solved if we avoid the root concatenation on ETController, 768:

```
// else foreach ($files as &$file) $file = PATH_ROOT."/".$file;
else foreach ($files as &$file) if (strpos($file, '://') === false) $file = PATH_ROOT."/".$file;
```

And ETController, 773, removing the extra question mark, due to lack of PHP capability of get external file timestamp:

```
// $head .= "<link rel='stylesheet' href='".getResource($file)."?".filemtime($file)."'>\n";
$head .= "<link rel='stylesheet' href='".rtrim(getResource($file)."?".filemtime($file), '?')."'>\n";
```

I think the same goes to JS on ETController 785 and 790.

Sorry for my bad English. :)

**Comment by tobyzerner** [comment]
fixed in 5a75b02e560dc2c91dffdb493af890aeb1176c18
