### ISSUE TITLE
Attachment Plugin Not Working

### ISSUE THREAD

**Issue by grandmasta** [esotalk/esoTalk#89]
The Attachment Plugin is returning this error: Error uploading "logo_190x190.jpg": undefined.

**Comment by panxianhai** [comment]
First,check you php version,if yours is under php 5.4, my post is for you.

I got this problem also, and I find the line 12 of AttachmentController.class.php:

```
$attachmentId = explode("_", $attachmentId)[0];
```

require php 5.4, my php version is php 5.3.23.

then I change it to :

```
$attachmentId = explode("_", $attachmentId);
$attachmentId = $attachmentId[0];
```

It's works for me.

**Comment by vinayus** [comment]
mine is 5.4.3 version php but still getting same error... above doesnt help for me either.. :(

any help???

**Comment by CooperBarrett** [comment]
This solution does not work for me either ...

I'm stuck, can not attach files.

Please help me!

thank you

**Comment by psc** [comment]
Same problem, still 
Error uploading "xxxx": undefined.

**Comment by bensbox** [comment]
Did you guys check the folder permissions? Especially for the "uploads" directory and (if exists) the "attachments" directory?

If the webserver is able to write to those directories, please use the Firefox, with the Firebug extension and check what the request "http://www.example.com/esotalk/?p=attachment/upload" is returning as a raw response. Possibly no valid JSON object is being returned, which results into the "undefined" error.
Additionally you are able to check the Apache/NGINX error logs, if PHP itself is logging any errors.
