### ISSUE TITLE
Notification count increases when it shouldn't

### ISSUE THREAD

**Issue by tobyzerner** [esotalk/esoTalk#9]
The notification count number increases (and turns white) when you make a reply to a private or starred conversation.
1. Log in.
2. Start a private conversation with another member.
3. Get the other member to post a reply. You should receive a notification, and the notification count will increase. This is correct.
4. Reply to the private conversation. You will not receive a notification, but the notification count will still increase. This is incorrect. Upon opening your notifications, it will appear that there are no new notifications.

I believe this is happening because the notification count is based on the conversation lastPostTime. Since the lastPostTime is changed when you post a reply, you appear to receive a new notification.

**Comment by Nephets** [comment]
:) Good to see it's being addressed.
