### ISSUE TITLE
Screen hops to the top while hitting backspace

### ISSUE THREAD

**Issue by SirChillicious** [esotalk/esoTalk#90]
If I'm writing a longer post and hit backspace to fix some letters, the screen jumps back to the top of the new draft. I checked it with different members, everyone reports the same.

General: I love esoTalk, best, simple and easiest to use community software I ever used. Please continue your great work, I might donate something someday :)

**Comment by Hakaku** [comment]
This is related to this bug I had submitted (in the second part of the following post): https://github.com/esotalk/esoTalk/issues/85

I hope it gets fixed.
