### ISSUE TITLE
Missing option: Global conversations/posts

### ISSUE THREAD

**Issue by SirChillicious** [esotalk/esoTalk#91]
For e.g. rules which should be visible in every channel :)

**Comment by tobyzerner** [comment]
I don't think this feature is necessary - it kind of goes against the organisation principle behind channels. There are better ways to have "rules" appear globally. For example, a plugin could be made to show a message at the top of every page with a link to a rules conversation. I think a plugin already exists somewhere on the support forum which allows you to add links to the header.
