### ISSUE TITLE
forum/index.php/topic , why ?

### ISSUE THREAD

**Issue by jebarjonet** [esotalk/esoTalk#94]
The whole forum is working on, for example : 
http://mywebsite.fr/forum/index.php/1-welcome-to-discussions

and the link (correct, I guess, without the "index.php/") : 
http://mywebsite.fr/forum/1-welcome-to-discussions
doesn't work.

If you have a solution...

**Comment by ebukaezeh** [comment]
U need .htaccess and mod re_write to get friendly urls, ask for it on the official esotalk forum ( esotalk.org/forum) by starting a new conversation or by searching for it, if it has been asked before.
