### ISSUE TITLE
MYSQL_ATTR_DIRECT_QUERY

### ISSUE THREAD

**Issue by michelreyes** [esotalk/esoTalk#97]
Fatal error: Undefined class constant 'MYSQL_ATTR_DIRECT_QUERY' in C:\servidorweb\apache\htdocs\esoTalk\esoTalk-master\core\lib\ETDatabase.class.php on line 167

Line:#167
$this->connectionOptions[PDO::MYSQL_ATTR_DIRECT_QUERY] = true;

**Comment by tobyzerner** [comment]
What PHP version are you using? Is the PDO extension enabled?

**Comment by michelreyes** [comment]
I use PHP/5.4.11

and yes pdo line is without ";"
extension=php_pdo_mysql.dll

Any suggest?
Sorry for my english :)

**Comment by quangbahoa** [comment]
Tested on XAMPP/Windows 7 without errors.

**Comment by ciruz** [comment]
I tried to reproduce this issue on one of my server, and on one server i get exactly the same error. I can confirm it, but it's is server related, I will look into this tomorrow.

**Comment by ciruz** [comment]
@michelreyes and @quangbahoa can you please show your loaded php extensions?

``` php
<?php
    echo '<pre>'.print_r(get_loaded_extensions(), true).'</pre>';
?>
```

Please post the complete result.

**Comment by tvb** [comment]
fix with 

`yum --enablerepo=remi install php-pdo_mysql`

note: configure remi repo first.
